project:
  type: website
  output-dir: _site

website:
  title: "Programa de Formación Cientifica - Análisis Estadístico 2022"
  image: "ietsi-logo.png"
  favicon: "ietsi-logo.png"
  open-graph: true
  twitter-card: true
  # site-url: ""
  repo-url: https://github.com/psotob/ae-ietsi-2022/
  repo-actions: [edit, issue]
  page-navigation: true
  reader-mode: true
      
  page-footer:
      left: |
        Curso organizado por 
        [![](ietsi-logo.png){fig-alt="IETSI" width=65px}](https://ietsi.essalud.gob.pe/)
      center:
        - text: "EsSalud"
          url: http://www.essalud.gob.pe/
        - text: "IETSI"
          url: https://ietsi.essalud.gob.pe/
        - text: "R project"
          url: https://www.r-project.org/
        - text: "RStudio"
          url: https://www.rstudio.com/
        - text: "Tidyverse"
          url: https://www.tidyverse.org/    
        - text: "gtsummary"
          url: https://www.danieldsjoberg.com/gtsummary/  
      right:
        - icon: twitter
          href: https://twitter.com/percysotobecer1
          aria-label: Percy Soto-Becerra Twitter
        - icon: github
          href: https://github.com/psotob
          aria-label: Percy Soto-Becerra Github
      border: true
      background: light
    
  navbar:
    background: light
    search: true
    logo: ietsi-logo.png
    title: false
    collapse-below: lg
    left:
      - href: programa.qmd
        text: Programa
      - href: cronograma.qmd
        text: Cronograma
      - href: tareas.qmd
        text: Tareas 
      - href: recursos.qmd
        text: Recursos
  # sidebar:
  #   - id: get-started
  #     title: "Get Started"
  #     style: "floating"
  #     collapse-level: 2
  #     align: left
  #     contents:
  #       - docs/get-started/index.qmd
  #       - text: "Tutorial: Hello, Quarto"
  #         href: docs/get-started/hello/
  #       - text: "Tutorial: Computations"
  #         href: docs/get-started/computations/
  #       - text: "Tutorial: Authoring"
  #         href: docs/get-started/authoring/
  # 
  #   - id: guide
  #     collapse-level: 1
  #     contents:
  #       - text: "Guide"
  #         href: docs/guide/index.qmd
  #       - section: "Authoring"
  #         contents:
  #           - docs/authoring/markdown-basics.qmd
  #           - docs/authoring/figures.qmd
  #           - docs/authoring/tables.qmd
  #           - docs/authoring/diagrams.qmd
  #           - docs/authoring/callouts.qmd
  #           - docs/authoring/article-layout.qmd
  #           - section: "Scholarly Writing"
  #             contents:
  #               - docs/authoring/title-blocks.qmd
  #               - docs/authoring/footnotes-and-citations.qmd
  #               - docs/authoring/cross-references.qmd
  #               - docs/authoring/create-citeable-articles.qmd
  #               - docs/authoring/appendices.qmd
  #       - section: "Computations"
  #         contents:
  #           - docs/computations/python.qmd
  #           - docs/computations/r.qmd
  #           - docs/computations/julia.qmd
  #           - docs/computations/ojs.qmd
  #           - docs/computations/execution-options.qmd
  #           - docs/computations/parameters.qmd
  #       - section: "Formats"
  #         contents:
  #           - section: "HTML"
  #             contents:
  #               - docs/output-formats/html-basics.qmd
  #               - docs/output-formats/html-code.qmd
  #               - docs/output-formats/html-themes.qmd
  #               - docs/output-formats/html-publishing.qmd
  #           - section: "PDF"
  #             contents:
  #               - docs/output-formats/pdf-basics.qmd
  #               - docs/output-formats/pdf-engine.qmd
  #           - section: "MS Word"
  #             contents:
  #               - docs/output-formats/ms-word.qmd
  #               - docs/output-formats/ms-word-templates.qmd
  #           - section: "Presentations"
  #             contents:
  #               - text: "Overview"
  #                 href: docs/presentations/index.qmd
  #               - section: docs/presentations/revealjs/index.qmd
  #                 contents:
  #                   - text: "Reveal Basics"
  #                     href: docs/presentations/revealjs/index.qmd
  #                   - docs/presentations/revealjs/presenting.qmd
  #                   - docs/presentations/revealjs/advanced.qmd
  #                   - docs/presentations/revealjs/themes.qmd
  #               - docs/presentations/powerpoint.qmd
  #               - docs/presentations/beamer.qmd
  #           - section: "Markdown"
  #             contents:
  #               - docs/output-formats/gfm.qmd
  #               - docs/output-formats/hugo.qmd
  #           - docs/output-formats/all-formats.qmd
  #       - section: "Tools"
  #         contents:
  #           - docs/tools/jupyter-lab.qmd
  #           - docs/tools/rstudio.qmd
  #           - docs/tools/vscode.qmd
  #           - docs/tools/text-editors.qmd
  #           - section: "Visual Editor"
  #             contents:
  #               - text: Editor Basics
  #                 href: docs/visual-editor/index.qmd
  #               - docs/visual-editor/technical.qmd
  #               - docs/visual-editor/content.qmd
  #               - docs/visual-editor/options.qmd
  #               - docs/visual-editor/markdown.qmd
  #       - section: "Interactivity"
  #         contents:
  #           - text: "Overview"
  #             href: docs/interactive/index.qmd
  #           - section: docs/interactive/ojs/index.qmd
  #             contents:
  #               - text: "Introduction"
  #                 href: docs/interactive/ojs/index.qmd
  #               - docs/interactive/ojs/libraries.qmd
  #               - docs/interactive/ojs/data-sources.qmd
  #               - docs/interactive/ojs/ojs-cells.qmd
  #               - docs/interactive/ojs/shiny.qmd
  #               - docs/interactive/ojs/code-reuse.qmd
  #               - section: "Examples"
  #                 contents:
  #                   - docs/interactive/ojs/examples/penguins.qmd
  #                   - docs/interactive/ojs/examples/sunburst.qmd
  #                   - docs/interactive/ojs/examples/arquero.qmd
  #                   - docs/interactive/ojs/examples/population.qmd
  #                   - docs/interactive/ojs/examples/noaa-co2.qmd
  #                   - docs/interactive/ojs/examples/github.qmd
  #                   - docs/interactive/ojs/examples/layout.qmd
  #                   - section: "Shiny"
  #                     contents:
  #                       - text: "K-Means"
  #                         href: https://jjallaire.shinyapps.io/kmeans-shiny-ojs/
  #                       - text: "Binning"
  #                         href: https://jjallaire.shinyapps.io/binning-shiny-ojs/
  #                       - text: "Data Binding"
  #                         href: https://jjallaire.shinyapps.io/data-shiny-ojs/
  #                       - text: "Covid Map"
  #                         href: https://jjallaire.shinyapps.io/covid19-bicartogram/
  #           - section: docs/interactive/shiny/index.qmd
  #             contents:
  #               - text: "Introduction"
  #                 href: docs/interactive/shiny/index.qmd
  #               - docs/interactive/shiny/running.qmd
  #               - docs/interactive/shiny/execution.qmd
  #               - docs/interactive/shiny/resources.qmd
  #               - section: "Examples"
  #                 contents:
  #                   - text: "Old Faithful"
  #                     href: https://jjallaire.shinyapps.io/shiny-old-faithful/
  #                   - text: "K-Means"
  #                     href: https://jjallaire.shinyapps.io/shiny-k-means/
  #                   - text: "Diamonds"
  #                     href: https://jjallaire.shinyapps.io/shiny-diamonds/
  #           - section: "Widgets"
  #             contents:
  #               - docs/interactive/widgets/jupyter.qmd
  #               - docs/interactive/widgets/htmlwidgets.qmd
  #           - docs/interactive/layout.qmd
  #       - section: "Projects"
  #         contents:
  #           - docs/projects/quarto-projects.qmd
  #           - docs/projects/code-execution.qmd
  #           - docs/projects/virtual-environments.qmd
  #       - section: "Websites"
  #         href: docs/websites/website-basics.qmd
  #         contents:
  #           - docs/websites/website-basics.qmd
  #           - docs/websites/website-navigation.qmd
  #           - docs/websites/website-blog.qmd
  #           - section: "Customizing Websites"
  #             href: docs/websites/website-search.qmd
  #             contents:
  #               - docs/websites/website-search.qmd
  #               - docs/websites/website-tools.qmd
  #               - docs/websites/website-about.qmd
  #           - section: "Listing Pages"
  #             href: docs/websites/website-listings.qmd
  #             contents:
  #               - docs/websites/website-listings.qmd
  #               - docs/websites/website-listings-custom.qmd
  #           - docs/websites/publishing-websites.qmd
  #       - section: "Books"
  #         href: docs/books/book-basics.qmd
  #         contents:
  #           - docs/books/book-basics.qmd
  #           - docs/books/book-structure.qmd
  #           - docs/books/book-crossrefs.qmd
  #           - text: "Customizing Output"
  #             href: docs/books/book-output.qmd
  #       - section: "Advanced"
  #         contents:
  #           - docs/authoring/includes.qmd
  #           - docs/authoring/variables.qmd
  #           - docs/output-formats/page-layout.qmd
  #           - docs/authoring/language.qmd
  #           - docs/authoring/conditional.qmd
  #       - section: "Extensions"
  #         contents:
  #           - docs/authoring/filters.qmd
  #           - docs/authoring/shortcodes.qmd
  # 
  #   - id: reference
  #     title: "Reference"
  #     contents:
  #       - text: "Reference"
  #         href: docs/reference/index.qmd
  #       - section: "Formats"
  #         contents:
  #           - text: "HTML"
  #             href: docs/reference/formats/html.qmd
  #           - text: "PDF"
  #             href: docs/reference/formats/pdf.qmd
  #           - text: "MS Word"
  #             href: docs/reference/formats/docx.qmd
  #           - text: "OpenOffice"
  #             href: docs/reference/formats/odt.qmd
  #           - text: "ePub"
  #             href: docs/reference/formats/epub.qmd
  #           - section: "Presentations"
  #             contents:
  #               - text: "Revealjs"
  #                 href: docs/reference/formats/presentations/revealjs.qmd
  #               - text: "PowerPoint"
  #                 href: docs/reference/formats/presentations/pptx.qmd
  #               - text: "Beamer"
  #                 href: docs/reference/formats/presentations/beamer.qmd
  #           - section: "Markdown"
  #             contents:
  #               - text: "GitHub"
  #                 href: docs/reference/formats/markdown/gfm.qmd
  #               - text: "CommonMark"
  #                 href: docs/reference/formats/markdown/commonmark.qmd
  #               - text: "Hugo"
  #                 href: docs/reference/formats/markdown/hugo.qmd
  #               - text: "Markua"
  #                 href: docs/reference/formats/markdown/markua.qmd
  #           - section: "Wikis"
  #             contents:
  #               - text: "MediaWiki"
  #                 href: docs/reference/formats/wiki/mediawiki.qmd
  #               - text: "DokuWiki"
  #                 href: docs/reference/formats/wiki/dokuwiki.qmd
  #               - text: "ZimWiki"
  #                 href: docs/reference/formats/wiki/zimwiki.qmd
  #               - text: "Jira Wiki"
  #                 href: docs/reference/formats/wiki/jira.qmd
  #               - text: "XWiki"
  #                 href: docs/reference/formats/wiki/xwiki.qmd
  #           - section: "More Formats"
  #             contents:
  #               - text: "JATS"
  #                 href: docs/reference/formats/jats.qmd
  #               - text: "Jupyter"
  #                 href: docs/reference/formats/ipynb.qmd
  #               - text: "ConTeXt"
  #                 href: docs/reference/formats/context.qmd
  #               - text: "RTF"
  #                 href: docs/reference/formats/rtf.qmd
  #               - text: "reST"
  #                 href: docs/reference/formats/rst.qmd
  #               - text: "AsciiDoc"
  #                 href: docs/reference/formats/asciidoc.qmd
  #               - text: "Org-Mode"
  #                 href: docs/reference/formats/org.qmd
  #               - text: "Muse"
  #                 href: docs/reference/formats/muse.qmd
  #               - text: "GNU TexInfo"
  #                 href: docs/reference/formats/texinfo.qmd
  #               - text: "Groff Man Page"
  #                 href: docs/reference/formats/man.qmd
  #               - text: "Groff Manuscript"
  #                 href: docs/reference/formats/ms.qmd
  #               - text: "Haddock markup"
  #                 href: docs/reference/formats/haddock.qmd
  #               - text: "OPML"
  #                 href: docs/reference/formats/opml.qmd
  #               - text: "Textile"
  #                 href: docs/reference/formats/textile.qmd
  #               - text: "DocBook"
  #                 href: docs/reference/formats/docbook.qmd
  #               - text: "InDesign"
  #                 href: docs/reference/formats/icml.qmd
  #               - text: "TEI Simple"
  #                 href: docs/reference/formats/tei.qmd
  #               - text: "FictionBook"
  #                 href: docs/reference/formats/fb2.qmd
  #       - section: "Code Cells"
  #         contents:
  #           - text: "Jupyter"
  #             href: docs/reference/cells/cells-jupyter.qmd
  #           - text: "Knitr"
  #             href: docs/reference/cells/cells-knitr.qmd
  #           - text: "Observable"
  #             href: docs/reference/cells/cells-ojs.qmd
  #       - section: "Projects"
  #         contents:
  #           - text: "Options"
  #             href: docs/reference/projects/options.qmd
  #           - text: "Websites"
  #             href: docs/reference/projects/websites.qmd
  #           - text: "Books"
  #             href: docs/reference/projects/books.qmd
  #       - section: "More"
  #         contents:
  #           - text: "Dates"
  #             href: docs/reference/dates.qmd
  #           - text: "Globs"
  #             href: docs/reference/globs.qmd
  #           - text: "Citations"
  #             href: docs/reference/metadata/citation.qmd
      
format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    include-after-body: js.html

filters:
  - filters/include-files.lua
  - quarto

freeze: true

editor: source

