project:
  type: website
  output-dir: _site

website:
  title: "Programa de Formación Cientifica - Análisis Estadístico 2022"
  image: "ietsi-logo.png"
  favicon: "ietsi-logo.png"
  open-graph: true
  twitter-card: true
  site-url: https://ietsi-academy-aed.netlify.app/
  repo-url: https://github.com/psotob91/ae-ietsi-2022/
  repo-actions: [edit, issue]
  page-navigation: true
  reader-mode: true
      
  page-footer:
      left: |
        Curso organizado por 
        [![](ietsi-logo.png){fig-alt="IETSI" width=65px}](https://ietsi.essalud.gob.pe/)
      center:
        - text: "EsSalud"
          url: http://www.essalud.gob.pe/
        - text: "IETSI"
          url: https://ietsi.essalud.gob.pe/
        - text: "R project"
          url: https://www.r-project.org/
        - text: "RStudio"
          url: https://www.rstudio.com/
        - text: "tidyverse"
          url: https://www.tidyverse.org/    
        - text: "gtsummary"
          url: https://www.danieldsjoberg.com/gtsummary/  
      right:
        - icon: twitter
          href: https://twitter.com/psotob91
          aria-label: Percy Soto-Becerra Twitter
        - icon: github
          href: https://github.com/psotob91/ae-ietsi-2022
          aria-label: Course Web Page Github
      border: true
      background: light
    
  navbar:
    background: light
    search: true
    logo: ietsi-logo.png
    title: false
    collapse-below: lg
    left:
      - href: index.qmd
        text: "Inicio"
      - href: programa.qmd
        text: "Programa"
      - href: cronograma.qmd
        text: "Cronograma"
      - href: tareas/index.qmd
        text: "Tareas "
      - href: recursos/index.qmd
        text: "Recursos"
      - text: "Ayuda"
        menu: 
          - text: "Guía Instalación"
            href: manualr-ietsi.Rmd
          - text: "Reporta un Problema"
            icon: "bug"
            href: "https://github.com/psotob91/ae-ietsi-2022/issues/1"
          - text: "Foro de discusión/consultas"
            icon: "chat-right-text"
            href: "https://github.com/psotob91/ae-ietsi-2022/discussions"
          - text: "Licencia"
            href: "https://github.com/psotob91/ae-ietsi-2022/blob/main/LICENSE.md"
        
  sidebar:
      - id: tareas
        collapse-level: 1
        contents: 
          - text: "Tareas"
            href: tareas/index.qmd
          - section: "Problem Sets"
            contents: 
              - tareas/problem-set.qmd
              - tareas/problem-set/problem-set-1.qmd
              - tareas/problem-set/problem-set-2.qmd
              - tareas/problem-set/problem-set-3.qmd
              - tareas/problem-set/problem-set-4.qmd
          - section: "Evaluación Final"
            contents: 
              - tareas/evaluacion-final.qmd
              - tareas/evaluacion-final-sol.qmd
          - section: "Ejercicios Extras"
            contents: 
              - tareas/ejercicios-extras.qmd
              - tareas/ejercicios-extras/ejercicios-extras-dia1.qmd
              - tareas/ejercicios-extras/ejercicios-extras-dia2.qmd
              - tareas/ejercicios-extras/ejercicios-extras-dia3.qmd
              - tareas/ejercicios-extras/ejercicios-extras-dia4.qmd
              - tareas/ejercicios-extras/ejercicios-extras-dia5.qmd
              - tareas/ejercicios-extras/ejercicios-extras-dia6.qmd
              - tareas/ejercicios-extras/ejercicios-extras-dia7.qmd
              - tareas/ejercicios-extras/ejercicios-extras-dia8.qmd
      - id: recursos
        collapse-level: 1
        contents: 
          - text: "Recursos"
            href: recursos/index.qmd 
          - section: "Materiales de clase"
            contents: 
              - recursos/rec-sesion0.qmd
              - recursos/rec-sesion1.qmd
              - recursos/rec-sesion2.qmd
              - recursos/rec-sesion3.qmd
              - recursos/rec-sesion4.qmd
              - recursos/rec-sesion5.qmd
              - recursos/rec-sesion6.qmd
              - recursos/rec-sesion7.qmd
              - recursos/rec-sesion8.qmd
          - text: "Recursos en línea recomendados"
            href: recursos/enlinea/en-linea.qmd   
          - text: "Bibliografía recomendada según syllabus"
            href: recursos/syllabus/syllabus.qmd  
          - text: "Recursos en línea adicionales"
            href: recursos/adicionales/adicionales.qmd  
            
format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    include-after-body: js.html
    link-external-icon: false
    link-external-newwindow: true

filters:
  - filters/include-files.lua
  - quarto

freeze: true

editor: source

