---
title: "Cronograma"
lang: es
---

```{r}
#| echo: false
icons::fontawesome(name = "chalkboard", style = "solid") -> x
icons::fontawesome(name = "laptop-code", style = "solid") -> y
icons::fontawesome(name = "landmark", style = "solid") -> z
```

::: grid
`r icons::fontawesome$solid$chalkboard` Presentación

`r icons::fontawesome$solid$"laptop-code"` Código

`r icons::fontawesome$solid$landmark` Materiales
:::

::: {.callout-note collapse="true" icon="false"}
## MÓDULO 1

**ANÁLISIS DESCRIPTIVO Y PRINCIPIOS DE INFERENCIA**

+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+-------------+-------------+
| Fecha                | Tema                                                                                                                                                              | Presentación                                      | Código      | Materiales  |
+======================+===================================================================================================================================================================+:=================================================:+:===========:+:===========:+
| Junio 15, 2022       | -   Instalación de R y Rstudio                                                                                                                                    | [`` `r x` ``](../Sesiones/Sesion-1/Sesion-1.html) |             | `` `r z` `` |
|                      |                                                                                                                                                                   |                                                   |             |             |
|                      | -   Manejo básico                                                                                                                                                 |                                                   |             |             |
|                      |                                                                                                                                                                   |                                                   |             |             |
|                      | -   Inspección inicial de datos y análisis descriptivo                                                                                                            |                                                   |             |             |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+-------------+-------------+
|                      | -   Taller de inspección inicial de datos y análisis descriptivo.                                                                                                 |                                                   | `` `r y` `` |             |
|                      |                                                                                                                                                                   |                                                   |             |             |
|                      | -   Creación automatizada de Tabla 1 reproducible (R: gtsummary)                                                                                                  |                                                   |             |             |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+-------------+-------------+
| Junio 17, 2022       | -   Revisión de inferencia estadística: Pruebas de hipótesis paramétricas y no paramétricas para un grupo y dos grupos.                                           | `` `r x` ``                                       |             | `` `r z` `` |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+-------------+-------------+
|                      | -   Taller sobre estimación y prueba de hipótesis e intervalos de confianza para uno o dos grupos.                                                                |                                                   | `` `r y` `` |             |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+-------------+-------------+
| Junio 22, 2022       | -   Revisión de inferencia estadística: Pruebas de hipótesis paramétricas y no paramétricas para tres o más grupos. Valor p e intervalo de confianza.             | `` `r x` ``                                       |             | `` `r z` `` |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+-------------+-------------+
|                      | -   Taller sobre estimación y prueba de hipótesis e intervalos de confianza para tres o más grupos. Creación automatizada de Tabla 2 reproducible (R: gtsummary). |                                                   | `` `r y` `` |             |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+-------------+-------------+
| Junio 15 al 24, 2022 | -   **Trabajo asincrónico. Desarrollo de 'Problem Set 1'.**                                                                                                       |                                                   |             |             |
+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+-------------+-------------+
:::

::: {.callout-note collapse="true" icon="false"}
## MÓDULO 2

**REGRESIÓN PARA DATOS NUMÉRICOS**

+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| Fecha                        | Tema                                                                                                                                            | Presentación | Código      | Materiales  |
+==============================+=================================================================================================================================================+:============:+:===========:+:===========:+
| Junio 24, 2022               | -   Introducción al modelado Bioestadístico. Objetivos de modelado: Descripción, Explicación y Predicción. Regresión Lineal Simple y múltiple.  | `` `r x` ``  |             | `` `r z` `` |
+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
|                              | -   Taller de RLM en R. Tabla 3 reproducible con gtsummary en R.                                                                                |              | `` `r y` `` |             |
+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| Junio 24 hasta Julio 1, 2022 | -   **Trabajo asincrónico. Desarrollo de 'Problem Set 2'.**                                                                                     |              |             |             |
+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
:::

::: {.callout-note collapse="true" icon="false"}
## MÓDULO 3

**REGRESIÓN PARA DESENLACES BINARIOS**

+----------------------+----------------------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| Fecha                | Tema                                                                                                                 | Presentación | Código      | Materiales  |
+======================+======================================================================================================================+:============:+:===========:+:===========:+
| Julio 1, 2022        | -   Introducción a la Regresión Logística Binaria.                                                                   | `` `r x` ``  |             | `` `r z` `` |
|                      |                                                                                                                      |              |             |             |
|                      | -   Interpretación y supuestos.                                                                                      |              |             |             |
+----------------------+----------------------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
|                      | -   Taller sobre Regresión Logística Binaria en R.                                                                   |              | `` `r y` `` |             |
|                      |                                                                                                                      |              |             |             |
|                      | -   Tablas reproducibles con gtsummary.                                                                              |              |             |             |
+----------------------+----------------------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| Julio 06, 2022       | -   Introducción a la regresión Log Binomial y Poisson para desenlaces binarios. Tablas reproducibles con gtsummary. | `` `r x` ``  |             | `` `r z` `` |
+----------------------+----------------------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
|                      | -   Taller sobre Regresión Log-Binomial y Poisson para desenlaces binarios en R. Tablas reproducibles con gtsummary. |              | `` `r y` `` |             |
+----------------------+----------------------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| Junio 01 al 10, 2022 | **Trabajo asincrónico. Desarrollo de 'Problem Set 3'**                                                               |              |             |             |
+----------------------+----------------------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
:::

::: {.callout-note collapse="true" icon="false"}
## MÓDULO 4

**REGRESIÓN PARA DESENLACES TIEMPO A EVENTO**

+----------------------+--------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| Fecha                | Tema                                                                                       | Presentación | Código      | Materiales  |
+======================+============================================================================================+:============:+:===========:+:===========:+
| Julio 8, 2022        | -   Introducción al análisis de tiempo a evento.                                           | `` `r x` ``  |             | `` `r z` `` |
|                      |                                                                                            |              |             |             |
|                      | -   Método de Kaplan-Meier y comparación de curvas de supervivencia.                       |              |             |             |
+----------------------+--------------------------------------------------------------------------------------------+--------------+-------------+-------------+
|                      | -   Taller sobre análisis de curvas de supervivencia en R.                                 |              | `` `r y` `` |             |
|                      |                                                                                            |              |             |             |
|                      | -   Tablas reproducibles desobrevida acumalada con gtsummary.                              |              |             |             |
|                      |                                                                                            |              |             |             |
|                      | -   Gráficos de KM con survminer.                                                          |              |             |             |
+----------------------+--------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| Julio 13, 2022       | -   Introducción al análisis de regresión de Cox. Supuestos. Interpretación de resultados. | `` `r x` ``  |             | `` `r z` `` |
+----------------------+--------------------------------------------------------------------------------------------+--------------+-------------+-------------+
|                      | -   Taller sobre análisis de regresión de Cox.                                             |              | `` `r y` `` |             |
|                      |                                                                                            |              |             |             |
|                      | -   Tablas reproducibles con gtsummary.                                                    |              |             |             |
+----------------------+--------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| Junio 08 al 20, 2022 | **Trabajo asincrónico. Desarrollo de 'Problem Set 4'**                                     |              |             |             |
+----------------------+--------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| Junio 20, 2022       | **Evaluación Final**                                                                       |              |             |             |
+----------------------+--------------------------------------------------------------------------------------------+--------------+-------------+-------------+
:::
