---
title: "Curso de Análisis Estadístico"
subtitle: "Programa de Formación Cientifica 2022"
page-layout: full
section-divs: false
toc: false
css: index.css
editor: source
---

::: grid
::: g-col-8
<p align="justify">Este sitio contiene el syllabus, cronograma, tareas y otros recursos para el curso **Análisis Estadístico** del **Programa de Formación Científica 2022** organizado por el **Instituto de Evaluación de Tecnologías en Salud e Investigación - IETSI** del **Seguro Social de Salud del Perú (EsSalud)**. Al finalizar el entrenamiento, el alumno estará en la capacidad de llevar a cabo un análisis exploratorio explicativo (factores asociados) o confirmatorio (efectividad clínica comparativa o evaluación de impacto) para desenlaces numéricos continuos, binarios y de tiempo a evento mediante un enfoque de modelado de regresión. El curso también busca promover y brindar recomendaciones sobre buenas prácticas de análisis bioestadístico con énfasis en principios de Ciencia Abierta y Reproducible.</p>
:::

::: g-col-4
**DOCENTE**<br>
`r icons::fontawesome("smile", style = "solid")` Percy Soto-Becerra<br> `r icons::fontawesome("envelope-open", style = "solid")` percys1991\@gmail.com<br> 
[`r icons::fontawesome$brands$orcid`](https://orcid.org/0000-0001-5332-9254) 0000-0001-5332-9254<br> 
[`r icons::fontawesome$brands$github`](https://github.com/psotob91) psotob91
:::
:::
