---
title: "Tareas"
lang: es
---

## Problem Sets

Aquí postearemos los Problem Set de acuerdo con el cronograma. Estos son calificados y, en conjunto, valen el 80% de la nota final (20% cada uno). Los participantes conformarán grupos de entre 5 o 6 personas. Se deberá enviar al correo electrónico los siguientes archivos:

#. Archivo RMarkdown con código de análisis.

#. Resultados del análisis en formato html (tal y como lo knitea RMarkdown).

#. Tablas reproducibles en Microsoft Office (tal como son generadas por RMarkdown).

### Problem Set 1

Problem Set 1 será posteado el 15 de junio de 2022.

### Problem Set 2

Problem Set 2 será posteado el 24 de junio de 2022.

### Problem Set 3

Problem Set 3 será posteado el 01 de julio de 2022.

### Problem Set 4

Problem Set 4 será posteado el 08 de julio de 2022.

## Evaluación Final

La evaluación final será posteada el 20 de julio de 2022. Esta es individual y tiene un 20% de la nota final. 

## Ejercicios Extras

Aquí postearemos ejercicios complementarios para ayudar a afianzar algunos conocimientos o competencias que los alumnos soliciten. Estos ejercicios no serán calificados. 