---
title: "Indicaciones"
lang: es
---

Aquí postearemos los Problem Set de acuerdo con el cronograma. Estos son calificados y, en conjunto, valen el 80% de la nota final (20% cada uno). 

Tener en cuenta lo siguiente: 

- Los participantes conformarán grupos de entre 5 o 6 personas de acuerdo con la lista proporcionada por la Coordinación del curso.

- Se deberá subir al siguiente enlace [https://redcap.link/ietsi-academy-aed](https://redcap.link/ietsi-academy-aed) una carpeta comprimida (.zip, .rar o .tar) los siguientes archivos:

    #. Archivo RMarkdown con código de análisis.
    
    #. Resultados del análisis en formato html (tal y como lo knitea RMarkdown).
    
    #. Tablas reproducibles en Microsoft Office (tal como son generadas por RMarkdown).

- Por cada 12 horas de retraso, se descontará 5 puntos a la calificación final del envío. Se calculará una fracción de penalización aplicando regla de 3 simple.

- No se tolerará el plagio ni ningún tipo de mala conducta académica. La detección de alguno de estos representará la expulsión automática del programa.