---
title: "Sesion 1"
---

## Diapositivas

- Sesión 1a [[Enlace](../Sesiones/Sesion-1/Sesion-1a.html)]

- Sesión 1b [[Enlace](../Sesiones/Sesion-1/Sesion-1b.html)]

- Sesión 1c [[Enlace](../Sesiones/Sesion-1/Sesion-1c.html)]

## Código para taller

- Taller 1:

    + Instrucciones: [[Enlace](../Sesiones/Sesion-1/Taller1.Rmd)]
    
    + R script: [[Enlace](../Sesiones/Sesion-1/Code/Taller1_sol.r)]
    
    + R notebook: [[Enlace](../Sesiones/Sesion-1/Code/Taller1_sol.Rmd)]

- Taller 2:

    + Instrucciones: [[Enlace](../Sesiones/Sesion-1/Taller2.Rmd)]

    + R script: [[Enlace](../Sesiones/Sesion-1/Code/Taller2_sol.r)]
    
    + R notebook: [[Enlace](../Sesiones/Sesion-1/Code/Taller2_sol.Rmd)]
    
## Datos 

- [BD_Penales.dta](https://github.com/culquichicon/2016-Peruvian-Prison-Census/blob/master/BD_Penales.dta?raw=true) (Datos contienen metadatos)

- [maca_meno_perclin.xlsx](../Data/maca_meno_perclin.xlsx) (Excel contiene `codebook` en otra hoja)

- [maca_meno_fase1.dta](../Data/maca_meno_fase1.dta) (Datos contienen metadatos)

- [indo_rct.rds]():
        
    + Instalar y cargar paquete [`medicaldata`](https://higgi13425.github.io/medicaldata/) y llamar usando la siguiente función: `indo_rct <- medicaldata::indo_rct`
        
    + `Codebook` en este [enlace](https://htmlpreview.github.io/?https://github.com/higgi13425/medicaldata/blob/master/man/codebooks/indo_rct_codebook.html)
        
    + `Descripción` en este [enlace](https://htmlpreview.github.io/?https://github.com/higgi13425/medicaldata/blob/master/man/description_docs/indo_rct_desc.html)