{
  "hash": "a3a6366078a7dcf71ab7b2dbb913a741",
  "result": {
    "markdown": "---\ntitle: \"<img data-src='images/logo-essalud.png' height='72' width='250'/> <img data-src='images/logo-pueblo.jpg' height='72' width='250'/> <img data-src='images/logo-ietsi.png' height='72' width='250'/> <FONT color='#232429'><br>Sesión 1c</FONT>\"\nsubtitle: \"<FONT color='#636363' size='7'>Programa de Formación Científica:<br>Análisis Estadístico 2022</FONT>\"\nauthor: \"<FONT color='#232429' size='30'>Percy Soto-Becerra</FONT>\"\ninstitute: \"<FONT color='#232429' size='5'>Instituto de Evaluación de Tecnologías en Salud e Investigación - IETSI, EsSalud<br>@github/psotob</FONT>\"\ndate: \"<FONT color='#232429' size='6'>Junio 15, 2022</FONT>\"\nformat: \n  revealjs: \n    theme: default\n    footer: \"Programa de Formación Científica: Análisis Estadístico 2022 - Sesión 1c\"\n    logo: images/logo-ietsi.png\n    transition: convex\n    background-transition: zoom\n    incremental: false\n    slide-number: true\n    preview-links: true\n    # parallax-background-image: images/bg-ietsi-slide-first.png\n    # parallax-background-size: \"1920px 1080px\"\n    chalkboard: true\n    code-block-background: true\n    code-block-border-left: \"#31BAE9\"\n    highlight-style: solarized\n    echo: true\n    multiplex: true\n    touch: true\n    auto-stretch: true\n    link-external-icon: true\n    link-external-newwindow: true\n---\n\n::: {.cell}\n\n:::\n\n\n## Análisis Exploratorio de Datos\n\n-   El `análisis exploratorio de datos` (AED) es un enfoque de análisis de conjunto de datos para `identificar patrones` y `formular nuevas hipótesis`.\n\n-   Se trata de ver `qué nos dice los datos` más allá de ideas pre-concebidas.\n\n-   Las `nuevas hipótesis` luego se `confirman` en `otros nuevos estudios` rigurosos.\n\n## Análisis Exploratorio de Datos (cont.)\n\n-   Su versión moderna: <FONT size='6'>\n    -   `Minería de Datos` ('Data Minning') </FONT>\n-   Usa diversas técnicas estadísticas: <FONT size='6'>\n    -   Medidas de resumen estadístico</FONT> <FONT size='6'>\n    -   Visualización de datos </FONT> <FONT size='6'>\n    -   Modelado </FONT>\n\n## Análisis Inicial de Datos\n\n-   El `análisis inicial de datos` (AID) a menudo se confunde `erróneamente` con el `AED`, son `dos enfoques totalmente diferentes`.\n\n-   Objetivo del AID:\n\n> <FONT size='6'>*\"(...) garantizar principalmente la `transparencia` y la `integridad` de las `condiciones previas` para realizar `análisis estadísticos apropiados` de manera responsable para responder `preguntas de investigación predefinidas`.\"* <br>*Baillie M, et al. [PLoS Comput Biol, 2022](https://doi.org/10.1371/journal.pcbi.1009819)*</FONT>\n\n## Análisis Inicial de Datos vs. Análisis Exploratorio de Datos\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"font-size: 30px; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> AID </th>\n   <th style=\"text-align:left;\"> AED </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1. AID es el paso inicial del proceso de confirmación de hipótesis pre-definidas. </td>\n   <td style=\"text-align:left;\"> 1. AED busca generar hipótesis nuevas. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 2. En investigación clínico-epidemiológica, a menudo queremos y deberíamos hacer AID. </td>\n   <td style=\"text-align:left;\"> 2. Rara vez queremos AED (p. ej., enfermedades nuevas, fenómenos muy poco conocidos) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 3. Proceso clave para garantizar responder adecuadamente objetivos pre-planeados de estudio. </td>\n   <td style=\"text-align:left;\"> 3. Proceso con alto riesgo de contaminar respuesta a objetivos pre-planeados de estudio. </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## `Mala práctica`: ¡Hacer AED en vez de AID!\n\n-   A menudo, investigadores `no realizan AID` de manera `sistemática`.\n-   `Mezclan actividades de AID` con tareas posteriores de análisis de datos, como generación o exploración de hipótesis, análisis formal e interpretación de conclusiones.\n-   Como se hacen \"informalmente\", no se reportan en detalle generándose `análisis ocultos`.\n\n::: aside\n<FONT size='4'>[*BMC Med Res Methodol 20, 61 (2020)*](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-020-00942-y)</FONT>\n:::\n\n## `Mala práctica`: ¡Hacer AED en vez de AID! (cont.)\n\n-   Estos `análisis ocultos` generan problemas en la reproducibilidad de los estudios.\n-   Generan `muchos grados de libertad adicionales` ocasionando `problemas serios` de validez de los análisis: *p-hacking*, *post-selection inference*, *double-dipping*, *overfitting*, *etc*.\n-   Iniciativa `STRATOS` ha dado pautas para realizar `AID` apropiados.\n\n::: aside\n<FONT size='4'>[*BMC Med Res Methodol 20, 61 (2020)*](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-020-00942-y)</FONT>\n:::\n\n## El problema de los análisis ocultos\n\n![<FONT size='4'>[*BMC Med Res Methodol 20, 61 (2020)*](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-020-00942-y)</FONT>](images/hidden.png)\n\n## Recomendaciones de STRATOS para hacer un buen AID\n\n![<FONT size='4'>[*PLoS Comput Biol 18(2): e1009819*](https://doi.org/10.1371/journal.pcbi.1009819)</FONT>](images/TenRules.png)\n\n## AID es un proceso iterativo\n\n-   Proceso no lineal, al contrario, requiere `muchas iteraciones`.\n\n-   <FONT color='red'>Riesgo</FONT>: Puede influir en análisis e inducir <FONT color='red'>conclusiones erróneas</FONT>. <FONT size='6'>\n\n    -   Mayor riesgo de restultados falsos positivos. </FONT>\n\n-   `Ser cuidados` para: <FONT size='6'>\n\n    -   Evitar alterar la pregunta de investigación. </FONT><FONT size='6'>\\\n    -   Proveer documentación completa del proceso. </FONT>\n\n## AID como parte del plan de investigación\n\n![<FONT size='4'>[*Introducing the Initial Data Analysis Topic Group (TG3)*](https://www.stratos-initiative.org/sites/default/files/2021-11/STRATOS-TG3-BB-initial-data-analysis.pdf)</FONT>](images/AID_plan.png)\n\n## AID como parte del plan de investigación\n\n![<FONT size='4'>[*Huebner M, Vach W, et al.*](https://www.jtcvs.org/action/showPdf?pii=S0022-5223%2815%2901794-8)</FONT>](images/AID_plan2.png)\n\n## 10 recomendaciones de STRATOS para un buen AID\n\n-   **Regla 1**: Desarrolle un `plan de AID` que respalde el `objetivo` de la investigación.\n\n-   **Regla 2**: AID toma `tiempo` y `recursos`.\n\n-   **Regla 3**: AID debe ser `reproducible`.\n\n-   **Regla 4**: El `contexto importa`, conoce tus datos.\n\n-   **Regla 5**: Evite los adelantos, AID `no toca la pregunta de investigación`.\n\n## 10 recomendaciones de STRATOS para un buen AID (cont.)\n\n-   **Regla 6**: `Visualiza` tus datos.\n\n-   **Regla 7**: `Compruebe` lo que falte.\n\n-   **Regla 8**: Comunicar los `hallazgos` y considerar las `consecuencias`.\n\n-   **Regla 9**: `Reporte` los hallazgos del AID en `trabajos de investigación` (¡adjunte `anexos`!)\n\n-   **Regla 10**: Sea `proactivo` y `riguroso`.\n\n## Análisis Inicial de Datos con R\n\n![](images/reglas-sol1.png)\n\n## Análisis Inicial de Datos con R\n\n![](images/reglas-sol2.png)\n\n## Regla 3: El contexto importa, conoce tus datos {.scrollable}\n\n-   Dé una primera `mirada global` a los datos\n-   Diseñe una `lista de validaciones` a realizar desde el proyecto.\n-   `Valida` tus datos: <FONT size='6'>\n    -   Identifique duplicados y detecte inconsistencias </FONT><FONT size='6'>\n    -   Valores extremos no plausibles </FONT><FONT size='6'>\n    -   Identifique valores perdidos </FONT>\\\n-   En `R`, use los 5 verbos básicos de {dplyr}: `filter()`, `select()`, `mutate()`, `arrange()` y `summarise()` para hacer `consultas` (`\"queries\"`) a sus datos.\n\n\n\n\n\n## Regla 3 con R: Resumen global de los datos {.scrollable}\n\n::: panel-tabset\n### glimpse()\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 26\nColumns: 13\n$ id_jaula     <dbl> 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 5, 5, 5, 5, 8, 8, 9, 9, 9, …\n$ id_raton     <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17…\n$ tratamiento  <chr> \"control\", \"control\", \"control\", \"control\", \"control\", \"m…\n$ protocolo    <chr> \"ovx\", \"ovx\", \"ovx\", \"hemiovx\", \"ovx\", \"ovx\", \"ovx\", \"ovx…\n$ peso_inicial <dbl> 26.00, 24.50, 20.40, 26.59, 23.50, 25.00, 24.80, 23.20, 2…\n$ peso_final   <dbl> 33.28, 30.50, 29.93, 32.19, 30.37, 30.43, 28.77, 27.30, 2…\n$ peso_utero   <dbl> 0.089, 0.063, 0.078, 0.134, 0.052, 0.055, 0.064, 0.062, 0…\n$ chol         <dbl> 85.990, 94.460, 99.670, 83.380, 82.080, 107.490, 76.870, …\n$ glucose      <dbl> 109.97, 81.62, 118.37, 71.91, 95.53, 160.36, 195.53, 182.…\n$ tag          <dbl> 182.42, 211.87, 195.16, 98.46, 108.13, 141.10, 95.82, 105…\n$ prot         <dbl> 5.37, 4.68, NA, NA, 5.33, NA, 5.02, 6.12, NA, 4.85, NA, N…\n$ urea         <dbl> 66.27, 76.73, 52.32, 50.71, 26.02, NA, 40.78, 66.94, NA, …\n$ album        <dbl> 66.82, 55.36, NA, NA, NA, 72.14, 67.09, 70.64, 66.27, 83.…\n```\n:::\n:::\n\n\n### contents()\n\n-   También de `Hmisc`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontents(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nData frame:datos\t26 observations and 13 variables    Maximum # NAs:13\n\n               Storage NAs\nid_jaula        double   0\nid_raton        double   0\ntratamiento  character   0\nprotocolo    character   0\npeso_inicial    double   0\npeso_final      double   0\npeso_utero      double   0\nchol            double   0\nglucose         double   0\ntag             double   0\nprot            double  12\nurea            double  10\nalbum           double  13\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhtml(contents(datos), levelType = 'table')\n```\n\n::: {.cell-output-display}\n```{=html}\n<hr><h4>Data frame:datos</h4>26 observations and 13 variables, maximum # NAs:13  \n <hr>\n <style>\n .hmisctable341165 {\n border: 1px solid gray;\n border-collapse: collapse;\n font-size: 100%;\n }\n .hmisctable341165 td {\n text-align: right;\n padding: 0 1ex 0 1ex;\n }\n .hmisctable341165 th {\n color: Black;\n text-align: center;\n padding: 0 1ex 0 1ex;\n font-weight: bold;\n }\n </style>\n <table class=\"hmisctable341165\" border=\"1\">\n <tr><th>Name</th><th>Storage</th><th>NAs</th></tr>\n <tr><td>id_jaula</td><td>double</td><td> 0</td></tr>\n <tr><td>id_raton</td><td>double</td><td> 0</td></tr>\n <tr><td>tratamiento</td><td>character</td><td> 0</td></tr>\n <tr><td>protocolo</td><td>character</td><td> 0</td></tr>\n <tr><td>peso_inicial</td><td>double</td><td> 0</td></tr>\n <tr><td>peso_final</td><td>double</td><td> 0</td></tr>\n <tr><td>peso_utero</td><td>double</td><td> 0</td></tr>\n <tr><td>chol</td><td>double</td><td> 0</td></tr>\n <tr><td>glucose</td><td>double</td><td> 0</td></tr>\n <tr><td>tag</td><td>double</td><td> 0</td></tr>\n <tr><td>prot</td><td>double</td><td>12</td></tr>\n <tr><td>urea</td><td>double</td><td>10</td></tr>\n <tr><td>album</td><td>double</td><td>13</td></tr>\n </table>\n\n <hr>\n\n```\n:::\n:::\n\n:::\n\n## Regla 3 con R: Detecte duplicados {.scrollable}\n\n-   Función `get_dupes` del paquete `{janitor}`.\n\n::: panel-tabset\n### Filas duplicadas\n\n-   Si solo colocamos `get_dupes()`, entonces nos identifica duplicados de fila completa:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(janitor)\ndatos %>% \n  get_dupes()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n  id_jaula id_raton tratamiento protocolo peso_inicial peso_final peso_utero\n     <dbl>    <dbl> <chr>       <chr>            <dbl>      <dbl>      <dbl>\n1        1        1 control     ovx               26         33.3      0.089\n2        1        1 control     ovx               26         33.3      0.089\n3        2        5 control     ovx               23.5       30.4      0.052\n4        2        5 control     ovx               23.5       30.4      0.052\n5        3        9 maca        hemiovx           22.7       26.9      0.07 \n6        3        9 maca        hemiovx           22.7       26.9      0.07 \n# … with 7 more variables: chol <dbl>, glucose <dbl>, tag <dbl>, prot <dbl>,\n#   urea <dbl>, album <dbl>, dupe_count <int>\n```\n:::\n:::\n\n\n### ID duplicados\n\n-   Si colocamos una o más variables dentro de `get_dupes()`, entonces nos identifica duplicados solo de esa variable.\n\n-   A menudo lo hacemos para encontrar individus duplicados.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos %>% \n  get_dupes(id_raton)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n  id_raton dupe_count id_jaula tratamiento protocolo peso_inicial peso_final\n     <dbl>      <int>    <dbl> <chr>       <chr>            <dbl>      <dbl>\n1        1          2        1 control     ovx               26         33.3\n2        1          2        1 control     ovx               26         33.3\n3        5          2        2 control     ovx               23.5       30.4\n4        5          2        2 control     ovx               23.5       30.4\n5        9          2        3 maca        hemiovx           22.7       26.9\n6        9          2        3 maca        hemiovx           22.7       26.9\n# … with 7 more variables: peso_utero <dbl>, chol <dbl>, glucose <dbl>,\n#   tag <dbl>, prot <dbl>, urea <dbl>, album <dbl>\n```\n:::\n:::\n\n\n### Elimine duplicados\n\n-   Si el duplicado es erróneo, lo podemos eliminar con `distinct` y el argumento `.keep_all = TRUE`.\n\n-   Se debde espeficiar si el duplicado es de fila o de alguna variable (p. ej., id).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos <- datos %>% \n  distinct(id_raton, .keep_all = TRUE)\n\ndatos\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 23 × 13\n   id_jaula id_raton tratamiento protocolo peso_inicial peso_final peso_utero\n      <dbl>    <dbl> <chr>       <chr>            <dbl>      <dbl>      <dbl>\n 1        1        1 control     ovx               26         33.3      0.089\n 2        1        2 control     ovx               24.5       30.5      0.063\n 3        1        3 control     ovx               20.4       29.9      0.078\n 4        2        4 control     hemiovx           26.6       32.2      0.134\n 5        2        5 control     ovx               23.5       30.4      0.052\n 6        2        6 maca        ovx               25         30.4      0.055\n 7        2        7 maca        ovx               24.8       28.8      0.064\n 8        3        8 maca        ovx               23.2       27.3      0.062\n 9        3        9 maca        hemiovx           22.7       26.9      0.07 \n10        3       10 maca        ovx               23.9       29.1      0.113\n# … with 13 more rows, and 6 more variables: chol <dbl>, glucose <dbl>,\n#   tag <dbl>, prot <dbl>, urea <dbl>, album <dbl>\n```\n:::\n:::\n\n:::\n\n## Regla 3 con R: Identifique valores extremos no plausibles {.scrollable}\n\n::: panel-tabset\n### skim()\n\n-   Función de paquete `{skimr}`:\n\n        1)  `install.packages(\"skimr)`\n\n        2)  `library(skimr)`\n\n-   Revise, variable por variable `valores extremos no plausibles` o `plausibles, pero sospechosamente extremos`. El valor mínimo es `p0` y el valor máximo es `p100`. Deben ser plausibles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(datos)\n```\n\n::: {.cell-output-display}\n<table style='width: auto;'\n      class='table table-condensed'>\n<caption>Data summary</caption>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Name </td>\n   <td style=\"text-align:left;\"> datos </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Number of rows </td>\n   <td style=\"text-align:left;\"> 23 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Number of columns </td>\n   <td style=\"text-align:left;\"> 13 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> _______________________ </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Column type frequency: </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> character </td>\n   <td style=\"text-align:left;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> numeric </td>\n   <td style=\"text-align:left;\"> 11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ________________________ </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Group variables </td>\n   <td style=\"text-align:left;\"> None </td>\n  </tr>\n</tbody>\n</table>\n\n\n**Variable type: character**\n\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> skim_variable </th>\n   <th style=\"text-align:right;\"> n_missing </th>\n   <th style=\"text-align:right;\"> complete_rate </th>\n   <th style=\"text-align:right;\"> min </th>\n   <th style=\"text-align:right;\"> max </th>\n   <th style=\"text-align:right;\"> empty </th>\n   <th style=\"text-align:right;\"> n_unique </th>\n   <th style=\"text-align:right;\"> whitespace </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> tratamiento </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 25 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> protocolo </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n</tbody>\n</table>\n\n\n**Variable type: numeric**\n\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> skim_variable </th>\n   <th style=\"text-align:right;\"> n_missing </th>\n   <th style=\"text-align:right;\"> complete_rate </th>\n   <th style=\"text-align:right;\"> mean </th>\n   <th style=\"text-align:right;\"> sd </th>\n   <th style=\"text-align:right;\"> p0 </th>\n   <th style=\"text-align:right;\"> p25 </th>\n   <th style=\"text-align:right;\"> p50 </th>\n   <th style=\"text-align:right;\"> p75 </th>\n   <th style=\"text-align:right;\"> p100 </th>\n   <th style=\"text-align:left;\"> hist </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> id_jaula </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> 5.30 </td>\n   <td style=\"text-align:right;\"> 3.38 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> 2.00 </td>\n   <td style=\"text-align:right;\"> 5.00 </td>\n   <td style=\"text-align:right;\"> 9.00 </td>\n   <td style=\"text-align:right;\"> 10.00 </td>\n   <td style=\"text-align:left;\"> ▇▃▅▂▇ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> id_raton </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> 12.00 </td>\n   <td style=\"text-align:right;\"> 6.78 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> 6.50 </td>\n   <td style=\"text-align:right;\"> 12.00 </td>\n   <td style=\"text-align:right;\"> 17.50 </td>\n   <td style=\"text-align:right;\"> 23.00 </td>\n   <td style=\"text-align:left;\"> ▇▆▇▆▇ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> peso_inicial </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> 23.68 </td>\n   <td style=\"text-align:right;\"> 1.99 </td>\n   <td style=\"text-align:right;\"> 18.90 </td>\n   <td style=\"text-align:right;\"> 22.59 </td>\n   <td style=\"text-align:right;\"> 23.50 </td>\n   <td style=\"text-align:right;\"> 24.90 </td>\n   <td style=\"text-align:right;\"> 27.90 </td>\n   <td style=\"text-align:left;\"> ▂▃▇▇▂ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> peso_final </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> 28.59 </td>\n   <td style=\"text-align:right;\"> 2.18 </td>\n   <td style=\"text-align:right;\"> 23.80 </td>\n   <td style=\"text-align:right;\"> 27.08 </td>\n   <td style=\"text-align:right;\"> 28.77 </td>\n   <td style=\"text-align:right;\"> 30.10 </td>\n   <td style=\"text-align:right;\"> 33.28 </td>\n   <td style=\"text-align:left;\"> ▂▆▇▅▂ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> peso_utero </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n   <td style=\"text-align:right;\"> 0.10 </td>\n   <td style=\"text-align:right;\"> 0.01 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n   <td style=\"text-align:right;\"> 0.54 </td>\n   <td style=\"text-align:left;\"> ▇▁▁▁▁ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> chol </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> 81.96 </td>\n   <td style=\"text-align:right;\"> 12.89 </td>\n   <td style=\"text-align:right;\"> 59.28 </td>\n   <td style=\"text-align:right;\"> 72.31 </td>\n   <td style=\"text-align:right;\"> 82.08 </td>\n   <td style=\"text-align:right;\"> 87.29 </td>\n   <td style=\"text-align:right;\"> 107.49 </td>\n   <td style=\"text-align:left;\"> ▅▃▇▃▃ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> glucose </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> 124.74 </td>\n   <td style=\"text-align:right;\"> 37.27 </td>\n   <td style=\"text-align:right;\"> 60.10 </td>\n   <td style=\"text-align:right;\"> 99.08 </td>\n   <td style=\"text-align:right;\"> 118.37 </td>\n   <td style=\"text-align:right;\"> 147.50 </td>\n   <td style=\"text-align:right;\"> 195.53 </td>\n   <td style=\"text-align:left;\"> ▅▇▇▃▅ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> tag </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1.00 </td>\n   <td style=\"text-align:right;\"> 153.06 </td>\n   <td style=\"text-align:right;\"> 52.36 </td>\n   <td style=\"text-align:right;\"> 90.99 </td>\n   <td style=\"text-align:right;\"> 108.13 </td>\n   <td style=\"text-align:right;\"> 141.10 </td>\n   <td style=\"text-align:right;\"> 190.11 </td>\n   <td style=\"text-align:right;\"> 282.64 </td>\n   <td style=\"text-align:left;\"> ▇▃▅▁▂ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> prot </td>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:right;\"> 0.52 </td>\n   <td style=\"text-align:right;\"> 5.22 </td>\n   <td style=\"text-align:right;\"> 0.49 </td>\n   <td style=\"text-align:right;\"> 4.68 </td>\n   <td style=\"text-align:right;\"> 4.91 </td>\n   <td style=\"text-align:right;\"> 5.08 </td>\n   <td style=\"text-align:right;\"> 5.34 </td>\n   <td style=\"text-align:right;\"> 6.17 </td>\n   <td style=\"text-align:left;\"> ▇▃▅▁▃ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> urea </td>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:right;\"> 0.61 </td>\n   <td style=\"text-align:right;\"> 56.95 </td>\n   <td style=\"text-align:right;\"> 32.34 </td>\n   <td style=\"text-align:right;\"> 26.02 </td>\n   <td style=\"text-align:right;\"> 38.87 </td>\n   <td style=\"text-align:right;\"> 48.16 </td>\n   <td style=\"text-align:right;\"> 64.80 </td>\n   <td style=\"text-align:right;\"> 157.89 </td>\n   <td style=\"text-align:left;\"> ▇▃▁▁▁ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> album </td>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:right;\"> 0.48 </td>\n   <td style=\"text-align:right;\"> 66.15 </td>\n   <td style=\"text-align:right;\"> 8.44 </td>\n   <td style=\"text-align:right;\"> 52.77 </td>\n   <td style=\"text-align:right;\"> 62.12 </td>\n   <td style=\"text-align:right;\"> 66.82 </td>\n   <td style=\"text-align:right;\"> 69.62 </td>\n   <td style=\"text-align:right;\"> 83.73 </td>\n   <td style=\"text-align:left;\"> ▃▃▇▂▂ </td>\n  </tr>\n</tbody>\n</table>\n:::\n:::\n\n\n### describe()\n\n-   Función de paquete `{Hmisc}`:\n\n        1)  `install.packages(\"Hmisc\")`\n\n        2)  `library(Hmisc)`\n\n-   Permite hacer algo similar\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndatos \n\n 13  Variables      23  Observations\n--------------------------------------------------------------------------------\nid_jaula \n       n  missing distinct     Info     Mean      Gmd \n      23        0        7    0.979    5.304    3.881 \n\nlowest :  1  2  3  5  8, highest:  3  5  8  9 10\n                                                    \nValue          1     2     3     5     8     9    10\nFrequency      3     4     3     4     2     4     3\nProportion 0.130 0.174 0.130 0.174 0.087 0.174 0.130\n--------------------------------------------------------------------------------\nid_raton \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n      23        0       23        1       12        8      2.1      3.2 \n     .25      .50      .75      .90      .95 \n     6.5     12.0     17.5     20.8     21.9 \n\nlowest :  1  2  3  4  5, highest: 19 20 21 22 23\n--------------------------------------------------------------------------------\ntratamiento \n       n  missing distinct \n      23        0        5 \n\nlowest : control                   maca                      maca + critro             sham operated             triple dosis maca + citro\nhighest: control                   maca                      maca + critro             sham operated             triple dosis maca + citro\n\ncontrol (5, 0.217), maca (5, 0.217), maca + critro (4, 0.174), sham operated\n(4, 0.174), triple dosis maca + citro (5, 0.217)\n--------------------------------------------------------------------------------\nprotocolo \n       n  missing distinct \n      23        0        3 \n                                  \nValue      hemiovx  no ovx     ovx\nFrequency        2       4      17\nProportion   0.087   0.174   0.739\n--------------------------------------------------------------------------------\npeso_inicial \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n      23        0       19    0.998    23.68    2.244    20.55    21.90 \n     .25      .50      .75      .90      .95 \n   22.59    23.50    24.90    25.90    26.53 \n\nlowest : 18.90 20.40 21.90 22.40 22.50, highest: 25.30 25.50 26.00 26.59 27.90\n                                                                            \nValue      18.90 20.40 21.90 22.40 22.50 22.69 22.90 23.20 23.40 23.50 23.90\nFrequency      1     1     2     1     1     1     1     1     2     2     1\nProportion 0.043 0.043 0.087 0.043 0.043 0.043 0.043 0.043 0.087 0.087 0.043\n                                                          \nValue      24.50 24.80 25.00 25.30 25.50 26.00 26.59 27.90\nFrequency      2     1     1     1     1     1     1     1\nProportion 0.087 0.043 0.043 0.043 0.043 0.043 0.043 0.043\n--------------------------------------------------------------------------------\npeso_final \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n      23        0       21    0.999    28.59    2.483    25.11    26.68 \n     .25      .50      .75      .90      .95 \n   27.08    28.77    30.10    30.49    32.02 \n\nlowest : 23.80 24.93 26.68 26.70 26.86, highest: 30.37 30.43 30.50 32.19 33.28\n--------------------------------------------------------------------------------\npeso_utero \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n      23        0       23        1   0.0927  0.07728   0.0166   0.0268 \n     .25      .50      .75      .90      .95 \n  0.0560   0.0680   0.0885   0.1298   0.1718 \n\nlowest : 0.014 0.016 0.022 0.046 0.052, highest: 0.108 0.113 0.134 0.176 0.535\n--------------------------------------------------------------------------------\nchol \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n      23        0       21    0.999    81.96     14.9    64.54    66.05 \n     .25      .50      .75      .90      .95 \n   72.31    82.08    87.29    98.89   104.36 \n\nlowest :  59.28  64.40  65.79  67.10  68.40, highest:  94.46  95.76  99.67 104.88 107.49\n--------------------------------------------------------------------------------\nglucose \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n      23        0       23        1    124.7    43.44    72.54    78.90 \n     .25      .50      .75      .90      .95 \n   99.08   118.37   147.50   179.63   184.30 \n\nlowest :  60.10  71.91  78.22  81.62  94.23, highest: 160.36 168.50 182.41 184.51 195.53\n--------------------------------------------------------------------------------\ntag \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n      23        0       22        1    153.1    59.41    93.45    96.35 \n     .25      .50      .75      .90      .95 \n  108.13   141.10   190.11   209.50   241.54 \n\nlowest :  90.99  93.19  95.82  98.46 105.49, highest: 199.12 200.00 211.87 244.84 282.64\n--------------------------------------------------------------------------------\nprot \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n      12       11       10    0.993    5.222   0.5367    4.735    4.787 \n     .25      .50      .75      .90      .95 \n   4.910    5.085    5.340    6.045    6.143 \n\nlowest : 4.68 4.78 4.85 4.93 5.02, highest: 5.15 5.33 5.37 6.12 6.17\n                                                                      \nValue       4.68  4.78  4.85  4.93  5.02  5.15  5.33  5.37  6.12  6.17\nFrequency      1     1     1     2     1     1     2     1     1     1\nProportion 0.083 0.083 0.083 0.167 0.083 0.083 0.167 0.083 0.083 0.083\n--------------------------------------------------------------------------------\nurea \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n      14        9       14        1    56.95    30.41    31.52    35.52 \n     .25      .50      .75      .90      .95 \n   38.87    48.16    64.80    73.79   105.14 \n\nlowest :  26.02  34.48  37.96  38.23  40.78, highest:  60.37  66.27  66.94  76.73 157.89\n                                                                         \nValue       26.02  34.48  37.96  38.23  40.78  43.06  45.61  50.71  52.32\nFrequency       1      1      1      1      1      1      1      1      1\nProportion  0.071  0.071  0.071  0.071  0.071  0.071  0.071  0.071  0.071\n                                             \nValue       60.37  66.27  66.94  76.73 157.89\nFrequency       1      1      1      1      1\nProportion  0.071  0.071  0.071  0.071  0.071\n--------------------------------------------------------------------------------\nalbum \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n      11       12       11        1    66.15    9.592    54.06    55.36 \n     .25      .50      .75      .90      .95 \n   62.12    66.82    69.62    72.14    77.94 \n\nlowest : 52.77 55.36 59.59 64.64 66.27, highest: 67.09 68.59 70.64 72.14 83.73\n                                                                            \nValue      52.77 55.36 59.59 64.64 66.27 66.82 67.09 68.59 70.64 72.14 83.73\nFrequency      1     1     1     1     1     1     1     1     1     1     1\nProportion 0.091 0.091 0.091 0.091 0.091 0.091 0.091 0.091 0.091 0.091 0.091\n--------------------------------------------------------------------------------\n```\n:::\n:::\n\n\n### Gráficos\n\n- El `gráfico de cajas` nos muestra la disrtibución de la variable numérica en termino de sus cuantiles.\n\n- Los `puntos aislados`, fuera de las cajas y bigotes, son considerados valores extremos. \n\n- Estos pueden ser `plausibles` o `no plausibles`. \n\n- El gráfico de cajas permite `identificar`, rápidamente, `valores extremos` potencialmente `no plausibles` o `problemáticos`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(datos$peso_final)\n```\n\n::: {.cell-output-display}\n![](Sesion-1c_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(datos$peso_utero)\n```\n\n::: {.cell-output-display}\n![](Sesion-1c_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n:::\n\n## Regla 3 con R: Haga algunas consultas (queries) de interés {.scrollable}\n\n::: panel-tabset\n### Consulta 1\n\nMuestre el peso inicial mínimo, máximo y promedio del grupo control:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2|3-7\"}\ndatos %>% \n  filter(tratamiento == \"control\") %>% \n  summarise(\n    minimo_peso = min(peso_inicial), \n    maximo_peso = max(peso_inicial), \n    promedio_peso = mean(peso_inicial)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 3\n  minimo_peso maximo_peso promedio_peso\n        <dbl>       <dbl>         <dbl>\n1        20.4        26.6          24.2\n```\n:::\n:::\n\n\n### Consulta 2\n\nMuestre los pesos inicial máximos, mínimo y promedio según grupo de tratamiento. También muestre el número de ratones por grupo:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2|3-7\"}\ndatos %>% \n  group_by(tratamiento) %>% \n  summarise(\n    minimo_peso = min(peso_inicial), \n    maximo_peso = max(peso_inicial), \n    promedio_peso = mean(peso_inicial), \n    n_ratones = n()\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 5\n  tratamiento               minimo_peso maximo_peso promedio_peso n_ratones\n  <chr>                           <dbl>       <dbl>         <dbl>     <int>\n1 control                          20.4        26.6          24.2         5\n2 maca                             22.7        25            23.9         5\n3 maca + critro                    21.9        23.4          22.4         4\n4 sham operated                    22.5        25.5          23.6         4\n5 triple dosis maca + citro        18.9        27.9          24.0         5\n```\n:::\n:::\n\n\n### Consulta 3\n\nMuestre los id_jaula con el número de ratones por jaula\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2|3\"}\ndatos %>% \n  group_by(id_jaula) %>% \n  summarise(n_ratones_por_jaula = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 × 2\n  id_jaula n_ratones_por_jaula\n     <dbl>               <int>\n1        1                   3\n2        2                   4\n3        3                   3\n4        5                   4\n5        8                   2\n6        9                   4\n7       10                   3\n```\n:::\n:::\n\n\n### Consulta 4\n\nIdentifique los ID de los ratones del grupo control con una razón glucosa / colesterol \\> 1\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2\"}\ndatos %>% \n  filter(tratamiento == \"control\" & glucose / chol > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 13\n  id_jaula id_raton tratamiento protocolo peso_inicial peso_final peso_utero\n     <dbl>    <dbl> <chr>       <chr>            <dbl>      <dbl>      <dbl>\n1        1        1 control     ovx               26         33.3      0.089\n2        1        3 control     ovx               20.4       29.9      0.078\n3        2        5 control     ovx               23.5       30.4      0.052\n# … with 6 more variables: chol <dbl>, glucose <dbl>, tag <dbl>, prot <dbl>,\n#   urea <dbl>, album <dbl>\n```\n:::\n:::\n\n\nOtra forma de hacerlo, es crear primerio la razón glucose / chol y filtrar:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2|3\"}\ndatos %>% \n  mutate(ratio_gluc_chol = glucose / chol) %>% \n  filter(tratamiento == \"control\" & ratio_gluc_chol > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 14\n  id_jaula id_raton tratamiento protocolo peso_inicial peso_final peso_utero\n     <dbl>    <dbl> <chr>       <chr>            <dbl>      <dbl>      <dbl>\n1        1        1 control     ovx               26         33.3      0.089\n2        1        3 control     ovx               20.4       29.9      0.078\n3        2        5 control     ovx               23.5       30.4      0.052\n# … with 7 more variables: chol <dbl>, glucose <dbl>, tag <dbl>, prot <dbl>,\n#   urea <dbl>, album <dbl>, ratio_gluc_chol <dbl>\n```\n:::\n:::\n\n:::\n\n## Análisis descriptivo\n\n-   Luego de AID uno ya está listo para describir sus datos.\n\n-   Hay muchas formas de describir datos, todos son combinación de `medidas de resumen` en `texto` y `tablas`, así como gràficos `gráficos`.\n\n-   Describir las `medidas` que faciliten la comparación de nuestra población de estudio con otras.\n\n## Análisis descriptivo de variable numérica {.scrollable}\n\n::: panel-tabset\n### Tend. Central\n-   Medias de tendencia central <FONT size='6'>\n    -   Media </FONT><FONT size='6'>\n    -   Mediana (es también `medida de posición`) </FONT><FONT size='6'>\n    -   Moda (no es usual) </FONT>\n    \n### Posición \n-   Medidas de posición <FONT size='6'>\n    -   Cuantiles (en general) </FONT><FONT size='6'> \n    -   Mediana = percentil 50 (es también medida de `tendencia central`) </FONT><FONT size='6'>\n    -   Percentil 25 (p25) </FONT><FONT size='6'>\n    -   Percentil 75 (p75) </FONT>\n    \n### Dispersión    \n-   Medidas de dispersión <FONT size='6'>\n    -   Rango (máximo - mínimo) </FONT><FONT size='6'>\n    -   Varianza / Desviación estándar </FONT><FONT size='6'>\n    -   Rango intercuartílico (p75 - p25) </FONT>    \n    \n### Distribución\n\n- Simétrica\n- Asimétrica (o 'sesgada')\n<FONT size='6'>\n    - Positiva (A la derecha) </FONT><FONT size='6'>\n    - Negativa (A la izquierda) </FONT>\n    \n- Resumiendo:\n\n![](images/distrib.png)\n:::\n\n## Análisis descriptivo de variable numérica - recomendaciones{.scrollable}\n\n::: panel-tabset\n### ¿Qué reportar?\n\n- `Media` +/- `Desviación estándar` <FONT size='6'>\n    - Si distribución es `simétrica` y `variabilidad es relativamente baja`. </FONT><FONT size='6'>\n    - La distribución normal es un ejemplo de distribución simétrica. </FONT>\n    \n- `Mediana` (`percentil 25` - `percentil 75`) <FONT size='6'>\n    - Si distribución es  `asimétrica` o `variabilidad es relativamente alta`. </FONT><FONT size='6'>\n    - Mejor `percentiles 25 y 75` en vez de rango intercuartílico (más información`de los primeros) </FONT> \n\n- `Máximo` y `mínimo` siempre: <FONT size='6'>\n    - Es mejor que rango, provee más información.</FONT><FONT size='6'>\n    - Preferentemente en `tabla principal`.</FONT><FONT size='6'>\n    - Si problemas de espacio, usar `tabla anexa`.</FONT>\n\n### Ejemplo 1\n\n**Para la variable numérica peso inicial** Se usa la función `skim()` y se coloca la variable de interés. \n\n  <FONT size='6'>\n  \n  - `p0` es el valor `mínimo` y `p100` es el valor `máximo`. </FONT><FONT size='6'>\n  \n  - La `mediana` es `p50`. </FONT><FONT size='6'>\n  \n  - `mean` es el `promedio` y `sd` es la `desviación estándar`. </FONT>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Para la variable numérica peso_inicial\ndatos %>% \n  skim(peso_inicial)\n```\n\n::: {.cell-output-display}\n<table style='width: auto;'\n      class='table table-condensed'>\n<caption>Data summary</caption>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Name </td>\n   <td style=\"text-align:left;\"> Piped data </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Number of rows </td>\n   <td style=\"text-align:left;\"> 23 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Number of columns </td>\n   <td style=\"text-align:left;\"> 13 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> _______________________ </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Column type frequency: </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> numeric </td>\n   <td style=\"text-align:left;\"> 1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ________________________ </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Group variables </td>\n   <td style=\"text-align:left;\"> None </td>\n  </tr>\n</tbody>\n</table>\n\n\n**Variable type: numeric**\n\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> skim_variable </th>\n   <th style=\"text-align:right;\"> n_missing </th>\n   <th style=\"text-align:right;\"> complete_rate </th>\n   <th style=\"text-align:right;\"> mean </th>\n   <th style=\"text-align:right;\"> sd </th>\n   <th style=\"text-align:right;\"> p0 </th>\n   <th style=\"text-align:right;\"> p25 </th>\n   <th style=\"text-align:right;\"> p50 </th>\n   <th style=\"text-align:right;\"> p75 </th>\n   <th style=\"text-align:right;\"> p100 </th>\n   <th style=\"text-align:left;\"> hist </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> peso_inicial </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 23.68 </td>\n   <td style=\"text-align:right;\"> 1.99 </td>\n   <td style=\"text-align:right;\"> 18.9 </td>\n   <td style=\"text-align:right;\"> 22.59 </td>\n   <td style=\"text-align:right;\"> 23.5 </td>\n   <td style=\"text-align:right;\"> 24.9 </td>\n   <td style=\"text-align:right;\"> 27.9 </td>\n   <td style=\"text-align:left;\"> ▂▃▇▇▂ </td>\n  </tr>\n</tbody>\n</table>\n:::\n:::\n\n\nTambién analizamos la `distribución` de manera gráfica con un histograma. Se aprecia que la variable es aproximadamente simétrica: \n\n<FONT size='6'>\n\n- Media vs mediana muy parecidas y </FONT><FONT size='6'>\n\n- Gráfico con desviaciones ligeras de simetría. </FONT>\n\nPor lo tanto, decidimos reportar `media (desviación estándar)`. `Mímimo` y `máximo` debería tambier reportarse (en texto o en tabla anexo).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(datos$peso_inicial)\n```\n\n::: {.cell-output-display}\n![](Sesion-1c_files/figure-revealjs/unnamed-chunk-20-1.png){width=960}\n:::\n:::\n\n\n**Descripción del resultado (ejemplo)**: \n\n> El peso inicial varió entre 18.9 g y 27.9 g, con un promedio de 23.68 g (DE = 1.99 g). \n\n### Ejemplo 2\n\n**Para la variable numérica triglicéridos al final del estudio**, se tiene las siguientes medidas de resumen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos %>% \n  skim(tag)\n```\n\n::: {.cell-output-display}\n<table style='width: auto;'\n      class='table table-condensed'>\n<caption>Data summary</caption>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Name </td>\n   <td style=\"text-align:left;\"> Piped data </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Number of rows </td>\n   <td style=\"text-align:left;\"> 23 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Number of columns </td>\n   <td style=\"text-align:left;\"> 13 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> _______________________ </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Column type frequency: </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> numeric </td>\n   <td style=\"text-align:left;\"> 1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ________________________ </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Group variables </td>\n   <td style=\"text-align:left;\"> None </td>\n  </tr>\n</tbody>\n</table>\n\n\n**Variable type: numeric**\n\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> skim_variable </th>\n   <th style=\"text-align:right;\"> n_missing </th>\n   <th style=\"text-align:right;\"> complete_rate </th>\n   <th style=\"text-align:right;\"> mean </th>\n   <th style=\"text-align:right;\"> sd </th>\n   <th style=\"text-align:right;\"> p0 </th>\n   <th style=\"text-align:right;\"> p25 </th>\n   <th style=\"text-align:right;\"> p50 </th>\n   <th style=\"text-align:right;\"> p75 </th>\n   <th style=\"text-align:right;\"> p100 </th>\n   <th style=\"text-align:left;\"> hist </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> tag </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 153.06 </td>\n   <td style=\"text-align:right;\"> 52.36 </td>\n   <td style=\"text-align:right;\"> 90.99 </td>\n   <td style=\"text-align:right;\"> 108.13 </td>\n   <td style=\"text-align:right;\"> 141.1 </td>\n   <td style=\"text-align:right;\"> 190.11 </td>\n   <td style=\"text-align:right;\"> 282.64 </td>\n   <td style=\"text-align:left;\"> ▇▃▅▁▂ </td>\n  </tr>\n</tbody>\n</table>\n:::\n:::\n\n\n\n- Notar que la `media` y la `mediana` difieren en aprox. `12 mg/dl`. Esto `sugiere` la existencia de alguna `asimetría` en la `distribución` de esta variable. \n\n- Veamos el gráfico:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(datos$tag)\n```\n\n::: {.cell-output-display}\n![](Sesion-1c_files/figure-revealjs/unnamed-chunk-22-1.png){width=960}\n:::\n:::\n\n\n- Se aprecia que la distribución es `sesgada hacia la derecha`. \n\n- Por lo tanto, la media no sería un buen `representante` de toda la distribución de datos. \n\n- La `mediana` es `más robusta` al sesgo de la distribución y `se prefiere` reportarla en compañía de los `percentiles 25` y `75`. \n\n**Descripción del resultado (ejemplo)**: \n\n> El nivel de triglicéridos al final del seguimiento varió entre 90.99 mg/dL y 282.64 mg/dL, con una mediana de 141.1 mg/dL (108.13 mg/dL a 190.11 mg/dL). \n\n::: \n\n## Análisis descriptivo de variable categórica{.scrollable}\n\n::: panel-tabset\n### ¿Qué reportar?\n\n-  Acompañe `siempre frecuencias absolutas` con `relativas`.\n\n-   Cuando interprete, no reporte solo % o proporción, también indique el n, al menos entre paréntesis.\n\n-   `Frecuencia absoluta`: Es el `número` de individuos.\n\n-   `Frecuencia relativa`: Es un `porcentaje` (entre 0% y 100%) o una `proporción` (entre 0 y 1).\n\n-   <FONT color='red'>Cuidado</FONT>: Reportar bien si es porcentaje (colocar <FONT color='red'>siempre</FONT> el %) o es una proporción (<FONT color='red'>nunca</FONT> colocar el %).\n\n- <FONT color='red'>Excepción</FONT>: En muestras que usan pesos muestrales, puede ser mejor solo reprotar frecuencias relativas (% o proporciones) y las frecuencias absolutas (observadas[no ponderadas] y ponderadas) dejarlas para el anexo.\n\n### Ejemplo 1\n\n- Podemos usar la función `tabyl()` del paquete `{janitor}` para describir la distribución de frecuencias relativas y acumuladas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos %>% \n  tabyl(tratamiento) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               tratamiento n   percent\n                   control 5 0.2173913\n                      maca 5 0.2173913\n             maca + critro 4 0.1739130\n             sham operated 4 0.1739130\n triple dosis maca + citro 5 0.2173913\n```\n:::\n:::\n\n\n- La columna `percent()` es en realidad una proporción. Para reportar un `porcentaje`, se puede agregar `adorn_pct_formatting()`: \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos %>% \n  tabyl(tratamiento) %>% \n  adorn_pct_formatting()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               tratamiento n percent\n                   control 5   21.7%\n                      maca 5   21.7%\n             maca + critro 4   17.4%\n             sham operated 4   17.4%\n triple dosis maca + citro 5   21.7%\n```\n:::\n:::\n\n\n**Descripción del resultado (ejemplo)**: \n\n> Los grupos control, maca y triple dosis maca + citro representaron el 21.7% (n = 5) de los animales de experimentación. \n\n### Ejemplo 2\n\n\n::: {.cell}\n\n:::\n\n\n- Para la variable `Glucosa categorizada` tenemos la siguiente distribución de frecuencias: \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos %>% \n  tabyl(glucose_cat) %>% \n  adorn_pct_formatting()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   glucose_cat  n percent\n 120-200 mg/dL 11   47.8%\n  60-120 mg/dL 12   52.2%\n```\n:::\n:::\n\n\n- Se puede mejorar la presentación usando la función `gt()` del paquete `{gt}`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gt)\ndatos %>% \n  tabyl(glucose_cat) %>% \n  adorn_pct_formatting() %>% \n  gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ptukujmgro\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#ptukujmgro .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ptukujmgro .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ptukujmgro .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ptukujmgro .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ptukujmgro .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ptukujmgro .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ptukujmgro .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ptukujmgro .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ptukujmgro .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ptukujmgro .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ptukujmgro .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ptukujmgro .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ptukujmgro .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ptukujmgro .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ptukujmgro .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ptukujmgro .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ptukujmgro .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ptukujmgro .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ptukujmgro .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ptukujmgro .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ptukujmgro .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ptukujmgro .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ptukujmgro .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ptukujmgro .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ptukujmgro .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ptukujmgro .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ptukujmgro .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ptukujmgro .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ptukujmgro .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ptukujmgro .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ptukujmgro .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ptukujmgro .gt_left {\n  text-align: left;\n}\n\n#ptukujmgro .gt_center {\n  text-align: center;\n}\n\n#ptukujmgro .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ptukujmgro .gt_font_normal {\n  font-weight: normal;\n}\n\n#ptukujmgro .gt_font_bold {\n  font-weight: bold;\n}\n\n#ptukujmgro .gt_font_italic {\n  font-style: italic;\n}\n\n#ptukujmgro .gt_super {\n  font-size: 65%;\n}\n\n#ptukujmgro .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#ptukujmgro .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#ptukujmgro .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ptukujmgro .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#ptukujmgro .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#ptukujmgro .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">glucose_cat</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">percent</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">120-200 mg/dL</td>\n<td class=\"gt_row gt_right\">11</td>\n<td class=\"gt_row gt_left\">47.8%</td></tr>\n    <tr><td class=\"gt_row gt_left\">60-120 mg/dL</td>\n<td class=\"gt_row gt_right\">12</td>\n<td class=\"gt_row gt_left\">52.2%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n**Descripción del resultado (ejemplo)**: \n\n> El 52.2% (n = 12) de los animales de experimentación tuvo valores de glucosa entre 60 y 120 mg/dL. \n\n:::\n## Recomendaciones sobre reporte descriptivo según STROBE {.scrollable}\n\n- *`Strengthening the Reporting of Observational Studies in Epidemiology (STROBE)`* es una `guía de reporte` de `estudios observacionales` en `salud` mundialmente reconocida.\n\n- Las `revistas de alto impacto` solicitan que los investigadores se adhieran a estas guías y llenen un checklist.\n\n![<FONT size='4'>[Vanderbroucke JP, Elm Ev, Altman DG, et al. 2007](https://www.acpjournals.org/doi/epdf/10.7326/0003-4819-147-8-200710160-00010-w1)</FONT>](images/strobe.png)\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n- Lo que mencionamos acerca de reportar variables numéricas:\n:::\n\n::: {.column width=\"50%\"}\n![<FONT size='4'>[Vanderbroucke JP, Elm Ev, Altman DG, et al. 2007](https://www.acpjournals.org/doi/epdf/10.7326/0003-4819-147-8-200710160-00010-w1)</FONT>](images/strobe-description.png)\n:::\n:::: \n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n![<FONT size='4'>[Vanderbroucke JP, Elm Ev, Altman DG, et al. 2007](https://www.acpjournals.org/doi/epdf/10.7326/0003-4819-147-8-200710160-00010-w1)</FONT>](images/strobe-missing.png)\n:::\n\n::: {.column width=\"50%\"}\n- También debe reportarse el `número de participantes` con `datos perdidos` para cada variable de interés\n:::\n\n::::\n\n## Recomendaciones adicionales para mejorar un reporte descriptivo transparente según REMARK {.scrollable}\n\n-   *`Reporting Recommendations for Tumor Marker Prognostic Studies (REMARK)`* es una guía de reporte para estudios de marcadores pronósticos:\n<FONT size='6'>\n    - Inicialmente para cáncer. </FONT> <FONT size='6'>\n    - Debido a su amplio alcance, se usa en casi cualquier campo (p. ej., cardiología, neurología, etc.) donde se evalúe un marcador pronóstico.</FONT>\n\n![<FONT size='4'>[Sauerbrei W, Taube SE, McShane LM, et al. JNCI 2018](https://doi.org/10.1093/jnci/djy088)</FONT>](images/remark.png)\n\n\n![<FONT size='4'>[Sauerbrei W, Taube SE, McShane LM, et al. JNCI 2018](https://doi.org/10.1093/jnci/djy088)</FONT>](images/remark-description.png)\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n-   REMARK indica que `debe reportarse`  la `distribución` de los `marcadores` o `factores pronóstico` de interés y del `desenlace`: <FONT size='6'>\n    -   Biomarcador o score de predicción </FONT><FONT size='6'>\n    -   Desenlace </FONT>\n:::\n \n::: {.column width=\"50%\"}    \n![<FONT size='4'>[Sauerbrei W, Taube SE, McShane LM, et al. JNCI 2018](https://doi.org/10.1093/jnci/djy088)</FONT>](images/remark-distribution.png)    \n:::\n\n::::\n\n-   Lamentablemente es una mala práctica no hacerlo. <FONT size='6'>\n    -   Usen anexos si el espacio queda corto y no quieren distraer al lector del mensaje principal. </FONT><FONT size='6'>\n    -   No hay excusa para no reportar esto. </FONT>\n\n## Recomendaciones adicionales para mejorar un reporte descriptivo transparente (cont.)\n\n-   No cree la tabla \"manualmente\".\n\n-   `Genere` las `tablas` con `código`: <FONT size='6'>\n\n    -   Es `reproducible`. </FONT><FONT size='6'>\n    -   Menos propenso a error de digitación o *`lapsus calamis`*. </FONT><FONT size='6'>\n    -   Han habido retracciones de ensayos clínicos por errores de tipeo!! </FONT><FONT size='6'>\n    -   Es más rápido, ahorrarás tiempo!! </FONT>\n\n## Generación de tabla descriptiva reproducible \n\n-   A menudo se la conoce como `la Tabla 1`. <FONT size='6'>\n    -   Puede haber más de una, no hay reglas, solo buenos o malos criterios para presentar resultados. </FONT>\n-   Hay muchos paquetes: `{flextable}`, `{gt}`, etc.\n-   Sugerimos: `{gtsummary}`: [https://www.danieldsjoberg.com/gtsummary/](https://www.danieldsjoberg.com/gtsummary/)\n\n## Tabla decriptiva reproducible con {gtsummary}\n\n-   Permite `crear tablas` en formato de `revistas biomédicas`.\n\n-   Función `tbl_summary()` para tablas descriptivas univariadas y comparativas (bivariadas)\n\n<center>![](images/tbl_summary_demo1.gif)</center>\n\n## Función tbl_summary() paso a paso {.scrollable}\n\n::: panel-tabset\n\n### Paso 1\n\n- Seleccionar las variables que desea reportar con función `select()`, luego usar `tbl_summary()`:\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2|3|4|\"}\nlibrary(gtsummary)\ndatos2 %>% \n  select(age, race, married2, weight, height, e2, lh, fsh, prog) %>% \n  tbl_summary()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"pifiisynzb\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#pifiisynzb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pifiisynzb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pifiisynzb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pifiisynzb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pifiisynzb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pifiisynzb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pifiisynzb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pifiisynzb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pifiisynzb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pifiisynzb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pifiisynzb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pifiisynzb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pifiisynzb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pifiisynzb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pifiisynzb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pifiisynzb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pifiisynzb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pifiisynzb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pifiisynzb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pifiisynzb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pifiisynzb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pifiisynzb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pifiisynzb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pifiisynzb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pifiisynzb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pifiisynzb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pifiisynzb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pifiisynzb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pifiisynzb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pifiisynzb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pifiisynzb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pifiisynzb .gt_left {\n  text-align: left;\n}\n\n#pifiisynzb .gt_center {\n  text-align: center;\n}\n\n#pifiisynzb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pifiisynzb .gt_font_normal {\n  font-weight: normal;\n}\n\n#pifiisynzb .gt_font_bold {\n  font-weight: bold;\n}\n\n#pifiisynzb .gt_font_italic {\n  font-style: italic;\n}\n\n#pifiisynzb .gt_super {\n  font-size: 65%;\n}\n\n#pifiisynzb .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#pifiisynzb .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#pifiisynzb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pifiisynzb .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#pifiisynzb .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#pifiisynzb .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\"><strong>N = 106</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">Age, years</td>\n<td class=\"gt_row gt_center\">33.0 (29.0, 37.0)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Race</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Mestiza</td>\n<td class=\"gt_row gt_center\">106 (100%)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Marital status, recat</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Without couple</td>\n<td class=\"gt_row gt_center\">54 (51%)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">With couple</td>\n<td class=\"gt_row gt_center\">52 (49%)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Weight, kg</td>\n<td class=\"gt_row gt_center\">59 (55, 65)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Unknown</td>\n<td class=\"gt_row gt_center\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\">Height, m</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">1.3</td>\n<td class=\"gt_row gt_center\">1 (1.0%)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">1.4</td>\n<td class=\"gt_row gt_center\">12 (12%)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">1.5</td>\n<td class=\"gt_row gt_center\">52 (50%)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">1.6</td>\n<td class=\"gt_row gt_center\">28 (27%)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">1.7</td>\n<td class=\"gt_row gt_center\">10 (9.7%)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Unknown</td>\n<td class=\"gt_row gt_center\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\">Estradiol</td>\n<td class=\"gt_row gt_center\">92 (59, 132)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Luteinizant Hormon</td>\n<td class=\"gt_row gt_center\">6 (3, 13)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Folicullo stimulant hormon</td>\n<td class=\"gt_row gt_center\">3.66 (2.12, 5.09)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Progesterone</td>\n<td class=\"gt_row gt_center\">10 (5, 12)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><sup class=\"gt_footnote_marks\">1</sup> Median (IQR); n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n- Por defecto, las `variables numéricas` son reportadas como `mediana` (`percentil 25`, `percentil 75`).\n\n- Asimismo, `si una variable numérica tiene pocos valores`, esta se muestra como `categórica`.\n\n- Uno puede `personalizar` esto. Veamos los siguientes pasos.\n\n### Paso 2\n\n- Indicar  `qué variables` son `numéricas` con el argumento `type = `\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|4|\"}\ndatos2 %>% \n  select(age, race, married2, weight, height, e2, lh, fsh, prog) %>% \n  tbl_summary(\n    type = list(height ~ \"continuous\")\n  )\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"nzdlxmawcy\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#nzdlxmawcy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nzdlxmawcy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nzdlxmawcy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nzdlxmawcy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nzdlxmawcy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nzdlxmawcy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nzdlxmawcy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nzdlxmawcy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nzdlxmawcy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nzdlxmawcy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nzdlxmawcy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nzdlxmawcy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nzdlxmawcy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nzdlxmawcy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nzdlxmawcy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nzdlxmawcy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nzdlxmawcy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nzdlxmawcy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nzdlxmawcy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nzdlxmawcy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nzdlxmawcy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nzdlxmawcy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nzdlxmawcy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nzdlxmawcy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nzdlxmawcy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nzdlxmawcy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nzdlxmawcy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nzdlxmawcy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nzdlxmawcy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nzdlxmawcy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nzdlxmawcy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nzdlxmawcy .gt_left {\n  text-align: left;\n}\n\n#nzdlxmawcy .gt_center {\n  text-align: center;\n}\n\n#nzdlxmawcy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nzdlxmawcy .gt_font_normal {\n  font-weight: normal;\n}\n\n#nzdlxmawcy .gt_font_bold {\n  font-weight: bold;\n}\n\n#nzdlxmawcy .gt_font_italic {\n  font-style: italic;\n}\n\n#nzdlxmawcy .gt_super {\n  font-size: 65%;\n}\n\n#nzdlxmawcy .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#nzdlxmawcy .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#nzdlxmawcy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nzdlxmawcy .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#nzdlxmawcy .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#nzdlxmawcy .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\"><strong>N = 106</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">Age, years</td>\n<td class=\"gt_row gt_center\">33.0 (29.0, 37.0)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Race</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Mestiza</td>\n<td class=\"gt_row gt_center\">106 (100%)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Marital status, recat</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Without couple</td>\n<td class=\"gt_row gt_center\">54 (51%)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">With couple</td>\n<td class=\"gt_row gt_center\">52 (49%)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Weight, kg</td>\n<td class=\"gt_row gt_center\">59 (55, 65)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Unknown</td>\n<td class=\"gt_row gt_center\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\">Height, m</td>\n<td class=\"gt_row gt_center\">1.50 (1.50, 1.60)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Unknown</td>\n<td class=\"gt_row gt_center\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\">Estradiol</td>\n<td class=\"gt_row gt_center\">92 (59, 132)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Luteinizant Hormon</td>\n<td class=\"gt_row gt_center\">6 (3, 13)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Folicullo stimulant hormon</td>\n<td class=\"gt_row gt_center\">3.66 (2.12, 5.09)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Progesterone</td>\n<td class=\"gt_row gt_center\">10 (5, 12)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><sup class=\"gt_footnote_marks\">1</sup> Median (IQR); n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n- Notar que ahora `height` es considerada una variable numérica y se reporta como `mediana` con sus respectivos `percentiles`. \n\n### Paso 3\n\n- ¿Qué pasa si queremos reportar `media` (`desviación estándar`) para las variables simétricas `height` y `weight`, pero mantener la `mediana` (`percentiles`) para las variables `e2`, `lh`, `fsh`, y `prog`. \n\n- Se puede configurar esto con el argumento `statistic = `\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|5|\"}\ndatos2 %>% \n  select(age, race, married2, weight, height, e2, lh, fsh, prog) %>% \n  tbl_summary(\n    type = list(height ~ \"continuous\"), \n    statistic = list(c(age, weight, height) ~ \"{mean} ({sd})\", c(e2, lh, fsh, prog) ~ \"{median} ({p25}, {p75})\")\n  )\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"hxvzwbwdeg\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#hxvzwbwdeg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hxvzwbwdeg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hxvzwbwdeg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hxvzwbwdeg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hxvzwbwdeg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hxvzwbwdeg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hxvzwbwdeg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hxvzwbwdeg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hxvzwbwdeg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hxvzwbwdeg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hxvzwbwdeg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hxvzwbwdeg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hxvzwbwdeg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hxvzwbwdeg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hxvzwbwdeg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hxvzwbwdeg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hxvzwbwdeg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hxvzwbwdeg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hxvzwbwdeg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hxvzwbwdeg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hxvzwbwdeg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hxvzwbwdeg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hxvzwbwdeg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hxvzwbwdeg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hxvzwbwdeg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hxvzwbwdeg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hxvzwbwdeg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hxvzwbwdeg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hxvzwbwdeg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hxvzwbwdeg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hxvzwbwdeg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hxvzwbwdeg .gt_left {\n  text-align: left;\n}\n\n#hxvzwbwdeg .gt_center {\n  text-align: center;\n}\n\n#hxvzwbwdeg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hxvzwbwdeg .gt_font_normal {\n  font-weight: normal;\n}\n\n#hxvzwbwdeg .gt_font_bold {\n  font-weight: bold;\n}\n\n#hxvzwbwdeg .gt_font_italic {\n  font-style: italic;\n}\n\n#hxvzwbwdeg .gt_super {\n  font-size: 65%;\n}\n\n#hxvzwbwdeg .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#hxvzwbwdeg .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#hxvzwbwdeg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hxvzwbwdeg .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#hxvzwbwdeg .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#hxvzwbwdeg .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\"><strong>N = 106</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">Age, years</td>\n<td class=\"gt_row gt_center\">32.8 (5.5)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Race</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Mestiza</td>\n<td class=\"gt_row gt_center\">106 (100%)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Marital status, recat</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Without couple</td>\n<td class=\"gt_row gt_center\">54 (51%)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">With couple</td>\n<td class=\"gt_row gt_center\">52 (49%)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Weight, kg</td>\n<td class=\"gt_row gt_center\">61 (8)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Unknown</td>\n<td class=\"gt_row gt_center\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\">Height, m</td>\n<td class=\"gt_row gt_center\">1.53 (0.08)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Unknown</td>\n<td class=\"gt_row gt_center\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\">Estradiol</td>\n<td class=\"gt_row gt_center\">92 (59, 132)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Luteinizant Hormon</td>\n<td class=\"gt_row gt_center\">6 (3, 13)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Folicullo stimulant hormon</td>\n<td class=\"gt_row gt_center\">3.66 (2.12, 5.09)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Progesterone</td>\n<td class=\"gt_row gt_center\">10 (5, 12)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><sup class=\"gt_footnote_marks\">1</sup> Mean (SD); n (%); Median (IQR)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Paso 4\n\n- Se pueden realizar `más configuraciones adicionales` con `R` o realizarlas `manualmente` en el Word.\n\n- Para más información sobre cómo hacer tablas descriptivas con `{gtsummary}`: [https://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html](https://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html)\n\n- Por ejemplo, podemos crear una tabla con `máximos` y `minimos`: \n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|5|\"}\ndatos2 %>% \n  select(age, race, married2, weight, height, e2, lh, fsh, prog) %>% \n  tbl_summary(\n    type = list(height ~ \"continuous\"), \n    statistic = list(c(age, weight, height, e2, lh, fsh, prog) ~ \"{min} - {max}\")\n  )\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"wyrwbgshnr\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#wyrwbgshnr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wyrwbgshnr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wyrwbgshnr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wyrwbgshnr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wyrwbgshnr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyrwbgshnr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wyrwbgshnr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wyrwbgshnr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wyrwbgshnr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wyrwbgshnr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wyrwbgshnr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wyrwbgshnr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wyrwbgshnr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wyrwbgshnr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wyrwbgshnr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wyrwbgshnr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wyrwbgshnr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyrwbgshnr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wyrwbgshnr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wyrwbgshnr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyrwbgshnr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wyrwbgshnr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wyrwbgshnr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyrwbgshnr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyrwbgshnr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wyrwbgshnr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wyrwbgshnr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyrwbgshnr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wyrwbgshnr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyrwbgshnr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wyrwbgshnr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyrwbgshnr .gt_left {\n  text-align: left;\n}\n\n#wyrwbgshnr .gt_center {\n  text-align: center;\n}\n\n#wyrwbgshnr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wyrwbgshnr .gt_font_normal {\n  font-weight: normal;\n}\n\n#wyrwbgshnr .gt_font_bold {\n  font-weight: bold;\n}\n\n#wyrwbgshnr .gt_font_italic {\n  font-style: italic;\n}\n\n#wyrwbgshnr .gt_super {\n  font-size: 65%;\n}\n\n#wyrwbgshnr .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#wyrwbgshnr .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#wyrwbgshnr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wyrwbgshnr .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#wyrwbgshnr .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#wyrwbgshnr .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\"><strong>N = 106</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">Age, years</td>\n<td class=\"gt_row gt_center\">20.0 - 41.0</td></tr>\n    <tr><td class=\"gt_row gt_left\">Race</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Mestiza</td>\n<td class=\"gt_row gt_center\">106 (100%)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Marital status, recat</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Without couple</td>\n<td class=\"gt_row gt_center\">54 (51%)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">With couple</td>\n<td class=\"gt_row gt_center\">52 (49%)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Weight, kg</td>\n<td class=\"gt_row gt_center\">48 - 92</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Unknown</td>\n<td class=\"gt_row gt_center\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\">Height, m</td>\n<td class=\"gt_row gt_center\">1.30 - 1.70</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Unknown</td>\n<td class=\"gt_row gt_center\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\">Estradiol</td>\n<td class=\"gt_row gt_center\">21 - 404</td></tr>\n    <tr><td class=\"gt_row gt_left\">Luteinizant Hormon</td>\n<td class=\"gt_row gt_center\">1 - 93</td></tr>\n    <tr><td class=\"gt_row gt_left\">Folicullo stimulant hormon</td>\n<td class=\"gt_row gt_center\">0.82 - 21.18</td></tr>\n    <tr><td class=\"gt_row gt_left\">Progesterone</td>\n<td class=\"gt_row gt_center\">0 - 28</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><sup class=\"gt_footnote_marks\">1</sup> Range; n (%)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Paso 5 \n\n- Se puede `descargar` la tabla en formato `MS. Word` para `reporte reproducible`.\n\n- Primero se  `guarda`  como un `objeto` de `R`:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|6|\"}\ndatos2 %>% \n  select(age, race, married2, weight, height, e2, lh, fsh, prog) %>% \n  tbl_summary(\n    type = list(height ~ \"continuous\"), \n    statistic = list(c(age, weight, height) ~ \"{mean} ({sd})\", c(e2, lh, fsh, prog) ~ \"{median} ({p25}, {p75})\")\n  ) -> tabla1 \n\ntabla1\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"yosknrapce\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#yosknrapce .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yosknrapce .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yosknrapce .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yosknrapce .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yosknrapce .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yosknrapce .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yosknrapce .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yosknrapce .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yosknrapce .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yosknrapce .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yosknrapce .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yosknrapce .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yosknrapce .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yosknrapce .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yosknrapce .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yosknrapce .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yosknrapce .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yosknrapce .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yosknrapce .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yosknrapce .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yosknrapce .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yosknrapce .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yosknrapce .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yosknrapce .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yosknrapce .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yosknrapce .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yosknrapce .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yosknrapce .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yosknrapce .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yosknrapce .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yosknrapce .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yosknrapce .gt_left {\n  text-align: left;\n}\n\n#yosknrapce .gt_center {\n  text-align: center;\n}\n\n#yosknrapce .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yosknrapce .gt_font_normal {\n  font-weight: normal;\n}\n\n#yosknrapce .gt_font_bold {\n  font-weight: bold;\n}\n\n#yosknrapce .gt_font_italic {\n  font-style: italic;\n}\n\n#yosknrapce .gt_super {\n  font-size: 65%;\n}\n\n#yosknrapce .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#yosknrapce .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#yosknrapce .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yosknrapce .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#yosknrapce .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#yosknrapce .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\"><strong>N = 106</strong><sup class=\"gt_footnote_marks\">1</sup></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">Age, years</td>\n<td class=\"gt_row gt_center\">32.8 (5.5)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Race</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Mestiza</td>\n<td class=\"gt_row gt_center\">106 (100%)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Marital status, recat</td>\n<td class=\"gt_row gt_center\"></td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Without couple</td>\n<td class=\"gt_row gt_center\">54 (51%)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">With couple</td>\n<td class=\"gt_row gt_center\">52 (49%)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Weight, kg</td>\n<td class=\"gt_row gt_center\">61 (8)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Unknown</td>\n<td class=\"gt_row gt_center\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\">Height, m</td>\n<td class=\"gt_row gt_center\">1.53 (0.08)</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"text-align: left; text-indent: 10px;\">Unknown</td>\n<td class=\"gt_row gt_center\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\">Estradiol</td>\n<td class=\"gt_row gt_center\">92 (59, 132)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Luteinizant Hormon</td>\n<td class=\"gt_row gt_center\">6 (3, 13)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Folicullo stimulant hormon</td>\n<td class=\"gt_row gt_center\">3.66 (2.12, 5.09)</td></tr>\n    <tr><td class=\"gt_row gt_left\">Progesterone</td>\n<td class=\"gt_row gt_center\">10 (5, 12)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><sup class=\"gt_footnote_marks\">1</sup> Mean (SD); n (%); Median (IQR)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n- Luego, al objeto se lo `guarda` como un archivo de `MS Word`. Para esto, se usa la función `as_flex_table()` del paquete `{gtsummary}` y la función `save_as_docx()` del paquete `{flextable}`: \n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|4|5|\"}\n# install.packages(flextable)\nlibrary(flextable)\ntabla1 %>% \n  as_flex_table() %>% \n  save_as_docx(path = \"Tabla1.docx\")\n```\n:::\n\n\n- El `MS Word` aparecerá en la `carpeta` del `proyecto`:\n\n![](images/tabla1-rstudio.png)\n\n- Y la `tabla` en `Word` lucirá así:\n\n![](images/tabla1-word.png)\n\n:::\n\n## \n\n::: r-fit-text\n<br>\n\n<center>\n\nslides:\n\n</center>\n\n<center>\n\n[https://bit.ly/3n6Ejzb](https://ietsi-academy-aed.netlify.app/sesiones/sesion-1/sesion-1c)\n\n</center>\n:::\n\n## \n\n::: r-fit-text\n<center>**¡Gracias por su atención!**</center>\n\n<center>**¡Encantado de responder sus consultas!**</center>\n\n<br>\n\n<center>**Percy Soto-Becerra**</center>\n\n<br>\n\n<center><svg viewBox=\"0 0 512 512\" style=\"height:1em;position:relative;display:inline-block;top:.1em;\" xmlns=\"http://www.w3.org/2000/svg\">  <path d=\"M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z\"></path></svg> <svg viewBox=\"0 0 496 512\" style=\"height:1em;position:relative;display:inline-block;top:.1em;\" xmlns=\"http://www.w3.org/2000/svg\">  <path d=\"M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z\"></path></svg> @psotob91</center>\n<center><svg viewBox=\"0 0 576 512\" style=\"height:1em;position:relative;display:inline-block;top:.1em;\" xmlns=\"http://www.w3.org/2000/svg\">  <path d=\"M567.938 243.908L462.25 85.374A48.003 48.003 0 0 0 422.311 64H153.689a48 48 0 0 0-39.938 21.374L8.062 243.908A47.994 47.994 0 0 0 0 270.533V400c0 26.51 21.49 48 48 48h480c26.51 0 48-21.49 48-48V270.533a47.994 47.994 0 0 0-8.062-26.625zM162.252 128h251.497l85.333 128H376l-32 64H232l-32-64H76.918l85.334-128z\"></path></svg> **percys1991\\@gmail.com**</center>\n:::\n\n::: aside\n<br> <FONT size='4'>Presentación creada vía `Revealjs` en `Quarto` en `RStudio`.</FONT>\n:::\n",
    "supporting": [
      "Sesion-1c_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\r\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\r\n"
      ],
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n\r\n      // dispatch for htmlwidgets\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for reveal\r\n    if (window.Reveal) {\r\n      window.Reveal.addEventListener(\"slidechanged\", function(event) {\r\n        fireSlideChanged(event.previousSlide, event.currentSlide);\r\n      });\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}